<?php if(isset($_SESSION['user'])){?>
<?php $header=$this->action('Application\Controller\IndexController', 'headerAction',array('20','10'));
	  $baseUrl = $header->headerarray['baseUrl'];
	  $basePath = $header->headerarray['basePath'];
	  $paypalUrl = $header->headerarray['paypalUrl'];
	  $paypalid = $header->headerarray['paypalid'];
?>
<div class="container">
	<div class="well"> 
		 <ul class="login-form-sec">
			<form id="ccavenue" method="post" action="https://www.ccavenue.com/shopzone/cc_details.jsp">
				<input type="hidden" name="Merchant_Id" value="Merchant_Id">
				<input type="hidden" name="Amount" value="Amount">
				<input type="hidden" name="Order_Id" value="Order_Id">
				<input type="hidden" name="Redirect_Url" value="success url">
				<input type="hidden" name="TxnType" value="A">
				<input type="hidden" name="ActionID" value="TXN">
				<input type="hidden" name="Checksum" value="<?php echo $Checksum; ?>">
				<input type="hidden" name="billing_cust_name" value="name of user">
				<input type="hidden" name="billing_cust_address" value="address of user">
				<input type="hidden" name="billing_cust_country" value="user country">
				<input type="hidden" name="billing_cust_state" value="state of user">
				<input type="hidden" name="billing_cust_city" value="city">
				<input type="hidden" name="billing_zip" value="zip/pin code">
				<input type="hidden" name="billing_cust_tel" value="telphone no">
				<input type="hidden" name="billing_cust_email" value="emailid">
				<input type="hidden" name="delivery_cust_name" value="user name">
				<input type="hidden" name="delivery_cust_address" value="delivering address">
				<input type="hidden" name="delivery_cust_country" value="delivering country">
				<input type="hidden" name="delivery_cust_state" value="delivering state">
				<input type="hidden" name="delivery_cust_tel" value="telphone no">
				<input type="hidden" name="delivery_cust_notes" value="this is a test">
				<input type="hidden" name="Merchant_Param" value="">
				<input type="hidden" name="billing_zip_code" value="zip/pin">
				<input type="hidden" name="delivery_cust_city" value="city">
				<input type="submit" value="pay Now" />
			</form>
		</ul>
	</div>
</div>
<script>
	alert("Please wait redirecting to pay pay site");
		$("#paypal-payment-form").submit();	
</script>
<?php }else{?>
<script>
	window.location=BASE_URL;
</script>
<?php } ?>