<div class="container mar_t">
	<script src="<?php echo $this->basepath;?>/js/ckeditor/ckeditor.js"></script>
	<style>
		.cke_textarea_inline
		{
			padding: 10px;
			height: 200px;
			overflow: auto;

			border: 1px solid gray;
			-webkit-appearance: textfield;
		}
    </style>
 
  <div class="modal-body">
          <form id="addIssue" class="form col-md-12 center-block" method="POST">
            <div class="form-group">
             <input type="text" name="title" class="form-control input-lg" id="title" value='<? if(isset($this->edit_issue[0]['issue_title'])){ echo $this->edit_issue[0]['issue_title']; }?>' placeholder="Issue Title" ><span id="errortitle" name="errortitle" style="color:red;" ></span>
            </div>
            <div class="form-group">
              <textarea name="article-body" class="form-control input-lg" id= "article-body" style="height:90px" placeholder="Description"  >
				<?php if(isset($this->edit_issue[0]['issue_decription'])){ echo $this->edit_issue[0]['issue_decription'];}?></textarea><span id="erroreditor" name="erroreditor" style="color:red;" ></span>
            </div>
			 <div class="form-group">
              <select id="category_id" name="category_id" class="form-control input-lg" >
				<option  value="" >Select Categories</option>
				<?php foreach($this->categories as $category){ 
				if($category['category_id']==$this->edit_issue[0]['category_id']){?>
				<option value="<?php echo $category['category_id'];?>" selected > <?php echo $category['category_name'];?></option>
				<?}else{?>
				<option value="<?php echo $category['category_id'];?>"  > <?php echo $category['category_name'];?></option>
				<?}}?>
			  </select>
				<span id="errorCat" name="errorCat" style="color:red;" ></span>
            </div>
            <div class="form-group">
			<? if(isset($this->edit_issue[0]['issue_id'])!=""){?>
				<button type="button" class="btn btn-primary btn-lg btn-bloconclick" onclick="addIssueFunction(1);">Update</button>&nbsp;<button type="button" class="btn btn-primary btn-lg btn-bloconclick" onclick="backFunction();">Back</button>
			<?}else{ ?>
				<button type="button" class="btn btn-primary btn-lg btn-bloconclick" onclick="addIssueFunction(0);">Add</button>&nbsp;<button type="button" class="btn btn-primary btn-lg btn-bloconclick" onclick="backFunction();">Back</button>
			<?}?>
			<input type="hidden" value="<?php echo $this->edit_issue[0]['issue_id'];?>" id="issue_id" name="issue_id" ></p>
			<input type="hidden" value="" id="hidbutton_value" name="hidbutton_value" >
            </div>
          </form>
      </div><div class="clearfix"></div>
</div>
	<script>
		CKEDITOR.inline( 'article-body' );
	function addIssueFunction(type){
		  var flag=true;
		  var title= $("#title").val();
		  var buttontype=$('#hidbutton_value').val(type);
		  var selectcat=$('#category_id').val();
		  if(title==""){
		     $("#errortitle").html("Required");
			 flag=false;
		  }else{
		      $("#errortitle").html("");
		  }
		  var ckeditor= CKEDITOR.instances['article-body'].getData().replace(/<[^>]*>/gi, '').length;
          if( !ckeditor ){
            $("#erroreditor").html("Required");
			 flag=false;
          }else{
		    $("#erroreditor").html(""); 
		  }
		  if(selectcat==""){
			$('#errorCat').html('Required');
			 flag=false;
		  }else{
			$('#errorCat').html('');
		  }
		  if(flag==true){
			$('#addIssue').submit();
		  }
	}
	function backFunction(){
		window.location=BASE_URL+'/admin/issues';
	}
	</script>