 <div class="container">

  <div id="loginModal" class="show"  role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <!--<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>-->
          <h1 class="text-center">Get In to Poorapo</h1>
      </div>
	  <div style="text_align:center;">
		<p><a href="category.phtml"></a></p>
		<p><a href="issues.phtml"></a></p>
	  </div>
     <div class="clearfix"></div>
  </div>
  </div>
</div>

    </div> <!-- /container -->