<div class="container">

  <div id="loginModal" class="show"  role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <!--<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>-->
          <h1 class="text-center">Add Category</h1>
      </div>
      <div class="modal-body">
          <form id="categoryForm" class="form col-md-12 center-block" method="POST">
            <div class="form-group">
              <input type="text" class="form-control input-lg" id="catname" name="catname" placeholder="Category Name" value="<?php echo $this->editcatdata->category_name; ?>">
			  <span id="emailError" style="color:red"></span>
            </div>
			<div class="form-group">
              <select class="form-control input-lg" id="cattype" name="cattypes" placeholder="please select category types">
			  <option value="1">CMS Page</option>
			  <option value="2">Header</option>
			  </select>
            </div>
            
            <div class="form-group">
              <button type="submit" class="btn btn-primary btn-lg btn-block" onclick="loginValidations(3);">Add Category</button>&nbsp;&nbsp;<span id="reload"></span>&nbsp;&nbsp;&nbsp;&nbsp;
            </div>
			<span id="errorMsg" style="color:red"></span>
          </form>
      </div><div class="clearfix"></div>
  </div>
  </div>
</div>

    </div> <!-- /container -->