 <div class="container">
  <div id="loginModal" class="show"  role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <!--<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>-->
          <h1 class="text-center">Get In to Poorapo</h1>
      </div>
      <div class="modal-body">
          <form id="loginForm" class="form col-md-12 center-block" method="POST">
            <div class="form-group">
              <input type="text" class="form-control input-lg" id="email" name="email" placeholder="Email">
			  <span id="emailError" style="color:red"></span>
            </div>
            <div class="form-group">
              <input type="password" class="form-control input-lg" id="password" name="password" placeholder="Password">
			  <span id="passwordError" style="color:red"></span>
            </div>
            <div class="form-group">
              <button type="button" class="btn btn-primary btn-lg btn-block" onclick="loginValidations(3);">Sign In</button>&nbsp;&nbsp;<span id="reload"></span>&nbsp;&nbsp;&nbsp;&nbsp;
            </div>
			<span id="errorMsg" style="color:red"></span>
          </form>
      </div><div class="clearfix"></div>
  </div>
  </div>
</div>

    </div> <!-- /container -->