<?php if(isset($_SESSION['user']['email'])){?>
<div class="container mar_t">
<head>
  <link rel="stylesheet" type="text/css" href="">
  <link href="<?php echo $basepath; ?>/css/jquery.datatable.css" rel="stylesheet">
  <script src="<?php echo $this->basepath;?>/js/jquery.datatable.min.js"></script>
</head>
<p><button type="button" class="btn btn-primary btn-bloconclick" id="add" name="add"  onclick="addissFunction();">Add</button>&nbsp;<button type="button" class="btn btn-primary btn-bloconclick" id="add" name="add"  onclick="backFunction(0);">Back</button></p>
<table id="example">
    <thead>
    <tr>
		 <th>Sno</th>
		 <th>IssuesTitle</th>
		 <th>IssuesDescription</th>
		 <th>Action</th>
	</tr>
    </thead>
    <tbody>
    </tbody>
</table>
<center><span id="reload"></span></center>
</div>
  <script>
$(function(){
$('#reload').html('<img src=<?php echo $basepath; ?>/images/ajax-loader.gif />');
  $.ajax({
		type		:	'GET',
		dataType	:   'json',
		url			:    BASE_PATH+'/admin/issuesAjax',
		success: function(data){
		$('#reload').html('');
			eval(data);
			var oTable = $('#example').dataTable( {
				aoColumnDefs: [{bSortable: false,
								aTargets: [ 0 ]
								}],
				"bStateSave": true,
				"bAutoWidth": true,
				"sRowSelect": "multi",
				"sPaginationType": "full_numbers",
				"bProcessing": true,
				"aaData": data,
				"aoColumns": [
					{ "mData": "sno" },
					{ "mData": "issue_title" },
					{ "mData": "issue_decription" },
					{ "mData": "action" }						
				] 
			});	
		}
	});
});
</script>
<?php }else{?>
  <script>window.location=BASE_URL+"/users/login";</script>
<?}?>
