<div class="container mar_t">
<head>
  <link rel="stylesheet" type="text/css" href="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/css/jquery.dataTables.css">
  <script type="text/javascript" charset="utf8" src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.2.min.js"></script>
  <script type="text/javascript" charset="utf8" src="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/jquery.dataTables.min.js"></script>
</head>
  <table id="example">
    <thead>
      <tr><th>Sno</th>
     <th>IssuesTitle</th>
     <th>IssuesDescription</th>
     <th>Action</th>
	 </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
  </div>
  <script>
  $(function(){
  $.ajax({
		type:	'GET',
		dataType:'json',
		url: BASE_PATH+'/admin/issues',
		success: function(data){
		alert(data);
			eval(data);
			var oTable = $('#example').dataTable( {
				aoColumnDefs: [{bSortable: false,
								aTargets: [ 0 ]
								}],
				"bStateSave": true,
				"bAutoWidth": true,
				"sRowSelect": "multi",
				"sPaginationType": "full_numbers",
				"bProcessing": true,
				"aaData": data,
				"aoColumns": [
					{ "mData": "sno" },
					{ "mData": "issue_title" },
					{ "mData": "issue_decription" },
					{ "mData": "action" }						
				] 
			});	
		}
	});
}
  </script>