<div class="container mar_t">
<head>
  <link rel="stylesheet" type="text/css" href="">
  <link href="<?php echo $basepath; ?>/css/jquery.datatable.css" rel="stylesheet">
  <script src="<?php echo $this->basepath;?>/js/jquery.datatable.min.js"></script>
</head>
<p><button type="button" class="btn btn-primary btn-lg btn-bloconclick" id="add" name="add"  onclick="addissFunction();">Add</button></p>

  <table id="example">
    <thead>
      <tr><th>Sno</th>
     <th>IssuesTitle</th>
     <th>IssuesDescription</th>
     <th>Action</th>
	 </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
  </div>
  <script>
  $(function(){
  $.ajax({
		type		:	'GET',
		dataType	:   'json',
		url			:    BASE_PATH+'/admin/issuesAjax',
		success: function(data){
			eval(data);
			var oTable = $('#example').dataTable( {
				aoColumnDefs: [{bSortable: false,
								aTargets: [ 0 ]
								}],
				"bStateSave": true,
				"bAutoWidth": true,
				"sRowSelect": "multi",
				"sPaginationType": "full_numbers",
				"bProcessing": true,
				"aaData": data,
				"aoColumns": [
					{ "mData": "sno" },
					{ "mData": "issue_title" },
					{ "mData": "issue_decription" },
					{ "mData": "action" }						
				] 
			});	
		}
	});
});
function addissFunction(){
window.location=BASE_URL+'/admin/addissue';
}

function deleteIssue(id){
window.location=BASE_URL+'/admin/issues?delid='+id;
}
function editIssue(edit_id){
	window.location=BASE_URL+'/admin/addissue?ediid='+edit_id;
}
</script>