<?php
	$header=$this->action('ZfcAdmin\Controller\AdminController', 'headerAction',array('20','10'));
	$baseUrl = $header->headerarray['baseUrl'];
	$basePath = $header->headerarray['basePath'];
?>
<script> 	
	var BASE_URL = '<?php echo $baseUrl;?>';
	var BASE_PATH = '<?php echo $basePath;?>';	
</script>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="<?php echo $basePath; ?>/favicon.ico">  
    <link href="<?php echo $basePath; ?>/css/bootstrap.css" rel="stylesheet">
    <link href="<?php echo $basePath; ?>/css/custom.css" rel="stylesheet">
    <link href="<?php echo $basePath; ?>/css/sticky-footer-navbar.css" rel="stylesheet">
  </head>
  <body>
    <!-- Fixed navbar -->
    <nav class="navbar-default-custom-c navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="index.html"><img src="<?php echo $basePath; ?>/img/logo.png" alt="Poorapo"/></h1></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories<span class="caret"></span></a>
			<ul class="dropdown-menu" role="menu">
                <li><a href="#">Education</a></li>
                <li><a href="#">Sports</a></li>
                <li><a href="#">Movies</a></li>
                <li><a href="#">News</a></li>
              </ul>
			</li>
			<li><a href="#contact">Contact</a></li>
            <li><a href="login.html">Get In</a></li>
            <li><a href="register.html" style="padding:0;margin-top:15px;margin-left:20px;"><span class="btn btn-default">Register</span></a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>