<?
global $forgotPwdPage;
$forgotPwdPage='Yes';
?>
<div class="body_main_container cat_top">
	<div class="body_middle_container">
		<div class=" form_top">
			<div class="row">
				<center>
					Email ID&nbsp;:&nbsp;<input type="text" class="text_pad" name="emailId" id="emailId"/>
					<p id="forgotPwdSbmt" class="fp_sbmt_btn"><a href="javascript:void(0)" class="btn" onClick="Javascript:checkFpEmailId();">SUBMIT</a></p>
					<p class="fp_sbmt_btn" id="loadingFp" style="display:none;"><img  style="vertical-align:middle;width:30px;" src="<?php echo $basePath; ?>/images/social_media/bx_loader.gif" />Mailing password reset link...</p>
					<p class="fp_home_link"><a href="/">Home Page</a></p>
				</center>
			</div>
		</div>
	</div>
</div>
