<?
global $forgotPwdPage;
$forgotPwdPage='Yes';
?>
<div class="body_main_container cat_top">
	<div class="body_middle_container">
		<div class=" form_top">
			<div class="row">
				<center>
					<?php
						if( isset($this->tokenExists) && ($this->tokenExists==1) )
						{
					?>
							<p class="reset_ml">New Password&nbsp;:&nbsp;<input type="password" class="text_pad" name="newPassword" id="newPassword"/></p>
							<div class="reset_cnf_div"><p>Confirm Password&nbsp;:&nbsp;<input type="password" class="text_pad" name="confirmPassword" id="confirmPassword"/></p></div>
							<p class="fp_sbmt_btn" id="resetPwdSbmt"><a href="javascript:void(0)" class="btn" onClick="Javascript:checkFpPassword();">RESET PASSWORD</a></p>
							<p class="fp_sbmt_btn" id="loadingFp" style="display:none;"><img  style="vertical-align:middle;width:30px;" src="<?php echo $basePath; ?>/images/social_media/bx_loader.gif" />Resetting your password...</p>
							<input type="hidden" id="hidtoken" name="hidtoken" value="<?echo $_GET['token'];?>"/>
					<?php
						}
						else
						{
					?>
							<p>Your link has expired.</p>
					<?php
						}
					?>
					<p class="fp_home_link"><a href="/">Home Page</a></p>
				</center>
			</div>
		</div>
	</div>
</div>
