<footer class="footer">
      <div class="container">
       <div class="row">
		  <div class="col-md-3">
			<h2>Navigation</h2>
			<ul class="list-unstyled">
				<li><a href="#">Home</a></li>
				<li><a href="#">About us</a></li>
				<li><a href="#">Company</a></li>
				<li><a href="#">Contact</a></li>
			</ul>
		  </div>
		  <div class="col-md-3">
			<h2>Other Links</h2>
			<ul class="list-unstyled">
				<li><a href="#">Terms & Conditions</a></li>
				<li><a href="#">Disclaimers</a></li>
				<li><a href="#">Privacy & Policies</a></li>
				<li><a href="#">Complaints & Grievance Redressal</a></li>
				<li><a href="#">Payments & Refunds</a></li>
			</ul>
		  </div>
		  <div class="col-md-3">
			<h2>Address</h2>
			<ul class="list-unstyled">
				<li>Plot No -5, Beside Vasireddy Swagruha Foods,Vivekananda nagar colony, Kukatapally.<br/>
				<a href="mailto:webmaster@example.com">Email: info@aapthitech.com</a><br/>
				<a href="#">Ph: +91 9908085654</a>
				</li>
			</ul>
		  </div>
		   <div class="col-md-3">
			<h2>Follow us</h2>
			<ul class="list-unstyled social_icons">
				<li><a href=""><a href="#"><img src="<?php echo $basePath; ?>/img/facebook.png" alt="facebook" title="Facebook"></a>
				<a href="#"><a href=""><img src="<?php echo $basePath; ?>/img/twitter.png" alt="twitter" title="Twitter"></a>
				<a href="#"><a href="#"><img src="<?php echo $basePath; ?>/img/google+.png" alt="google+" title="Google+"></a></li>
			</ul>
		  </div>
		</div>
      </div>
	  <div class="copy_right">
	  <div class="container">
		<p>Copyright &copy; 2015 Project name. All right reserved</p>
	  </div>
	  </div>
    </footer>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  
  </body>
</html>