<footer class="footer">
    <div class="container"> 
	<?php echo $footer; ?>
	</div>
	<div class="copy_right"> 
	<div class="container"> 
	<p>Copyright &copy; 2015 Poraapo.com. All right reserved</p>
	</div> 
	</div>	
    </footer>    
	<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-552e37574cbb9462" async="async"></script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-61839005-1', 'auto');
  ga('send', 'pageview');

</script>

  </body>
</html>