<footer class="footer">
    <div class="container"> 
	<?php echo $footer; ?>
	</div>
	<div class="copy_right"> 
	<div class="container"> 
	<p>Copyright &copy; 2015 Poraapo.com. All right reserved</p>
	</div> 
	</div>	
    </footer>    
	<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-552e37574cbb9462" async="async"></script>
  </body>
</html>