<?php
	$header=$this->action('Application\Controller\IndexController', 'headerAction',array('20','10'));
	$baseUrl = $header->headerarray['baseUrl'];
	$basePath = $header->headerarray['basePath'];
?>
<?php
	$header=$this->action('Application\Controller\IndexController', 'supplyHeaderCategoriesAction',array('30','40'));
	$categoriesArr = $header->catsInfoarray['categoriesArr'];
?>
<!DOCTYPE html>
<html lang="en">
  <head>  
	<script> 	
		var BASE_URL = '<?php echo $baseUrl;?>';
		var BASE_PATH = '<?php echo $basePath;?>';	
	</script>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="<?php echo $basePath; ?>/img/favicon.ico" type="image/x-icon">
	<link rel="icon" href="<?php echo $basePath; ?>/img/favicon.ico" type="image/x-icon">	
	<!-- CSS Start -->	
    <link href="<?php echo $basePath; ?>/css/bootstrap.css" rel="stylesheet">
    <link href="<?php echo $basePath; ?>/css/custom.css" rel="stylesheet">
    <link href="<?php echo $basePath; ?>/css/sticky-footer-navbar.css" rel="stylesheet">
	<!-- Js Script-->
	<script src="<?php echo $basePath; ?>/js/jquery-112min.js"></script>
    <script src="<?php echo $basePath; ?>/js/bootstrap.min.js"></script>
	<script src="<?php echo $basePath; ?>/js/isotope.pkgd.min.js"></script>
	<script src="<?php echo $basePath; ?>/js/poorapo.isotope.js"></script>
    <script src="<?php echo $basePath; ?>/js/commonfunctions.js"></script>
  </head>
  <body>
    <!-- Fixed navbar -->
    <nav class="navbar-default-custom-c navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<?php echo $baseUrl . '/'; ?>"><img src="<?php echo $basePath; ?>/img/logo.png" alt="Poorapo"/></h1></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories<span class="caret"></span></a>
			<ul class="dropdown-menu" role="menu"><?php if( isset($categoriesArr) )
					{
						foreach( $categoriesArr as $key=>$currentCategoryData )
						{
							$urlCatName = "";
							$currCatName = trim($currentCategoryData["category_name"]);
							$catNameArr = explode( " ",$currCatName );
							for( $catArrId = 0; $catArrId < count($catNameArr); $catArrId++ )
							{
								if( $catArrId > 0 )
								{
									$urlCatName .= "-";
								}
								$urlCatName .= trim($catNameArr[$catArrId]);
							}
							$catResultsUrl = $baseUrl . "/" . $urlCatName . "-" . $currentCategoryData["category_id"];
						?><li><a href="<?php echo $catResultsUrl; ?>"><?php echo trim($currentCategoryData["category_name"]); ?></a></li><?php }
					}?></ul>
			</li>
			<li><a href="#payments">Payments</a></li>
			<li><a href="#contact">Contact</a></li>
			<?php if(isset($_SESSION['user'])){?>
			<li><a href="#">Get Out</a></li>
			<?}else{?>
            <li><a href="<?php echo $baseUrl; ?>/users/login">Get In</a></li>
			<?}?>
            <li><a href="<?php echo $baseUrl; ?>/users/register" style="padding:0;margin-top:15px;margin-left:20px;"><span class="btn btn-default">Register</span></a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>