<?php
	$header=$this->action('Application\Controller\IndexController', 'headerAction',array('20','10'));
	$baseUrl = $header->headerarray['baseUrl'];
	$basePath = $header->headerarray['basePath'];
	$footer = $header->headerarray['footer'];	
	$loginActive = ''; $paymentActive = ''; $contactActive=''; $homeActive='';
	if(isset($_SERVER['HTTP_HOST']) && $_SERVER['HTTP_HOST']=='poraapo.com'){
		if($_SERVER['REQUEST_URI']=='/users/login'){
			$loginActive='active';		
		}else if($_SERVER['REQUEST_URI']=='/cms/Refunds-Payments-13'){
			$paymentActive ='active';
		}else if($_SERVER['REQUEST_URI']=='/users/contact-us'){
			$contactActive ='active';
		}else{
			$homeActive ='active';
		}
	}else{
		if($_SERVER['REQUEST_URI']=='/poorapo/trunk/users/login'){
			$loginActive='active';		
		}else if($_SERVER['REQUEST_URI']=='/poorapo/trunk/cms/Refunds-Payments-13'){
			$paymentActive ='active';
		}else if($_SERVER['REQUEST_URI']=='/poorapo/trunk/users/contact-us'){
			$contactActive ='active';
		}else{
			$homeActive ='active';
		}
	}
	
?>
<?php
	$header=$this->action('Application\Controller\IndexController', 'supplyHeaderCategoriesAction',array('30','40'));
	$categoriesArr = $header->catsInfoarray['categoriesArr'];
?>
<!DOCTYPE html>
<html lang="en">
  <head>  
  <title>Poraapo.com</title>
	<script> 	
		var BASE_URL = '<?php echo $baseUrl;?>';
		var BASE_PATH = '<?php echo $basePath;?>';	
	</script>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="http://www.poraapo.com/public/img/favicon.ico" type="image/x-icon">
	<link rel="icon" href="http://www.poraapo.com/public/img/favicon.ico" type="image/x-icon">	
	<!-- CSS Start -->	
    <link href="<?php echo $basePath; ?>/css/bootstrap.css" rel="stylesheet">
    <link href="<?php echo $basePath; ?>/css/custom.css" rel="stylesheet">
    <link href="<?php echo $basePath; ?>/css/sticky-footer-navbar.css" rel="stylesheet">
	<!-- Js Script-->	
	<script src="<?php echo $basePath; ?>/js/jquery-112min.js"></script>
    <script src="<?php echo $basePath; ?>/js/bootstrap.min.js"></script>
	<script src="<?php echo $basePath; ?>/js/isotope.pkgd.min.js"></script>
	<script src="<?php echo $basePath; ?>/js/poorapo.isotope.js"></script>
    <script src="<?php echo $basePath; ?>/js/commonfunctions.js"></script>
  </head>
  <body>
    <!-- Fixed navbar -->
    <nav class="navbar-default-custom-c navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
		  <?php if(isset($_SESSION['user'])){
			if($_SESSION['user']['user_type']==3){
		  ?>
			<a class="navbar-brand" href="<?php echo $baseUrl . '/admin/dashboard'; ?>"><img src="<?php echo $basePath; ?>/img/logo.png" alt="Poorapo"/></h1></a>
		  <?php }else{ ?>
			<a class="navbar-brand" href="<?php echo $baseUrl . '/'; ?>"><img src="<?php echo $basePath; ?>/img/logo.png" alt="Poorapo"/></h1></a>
		  <?php }}else{ ?>
		  <a class="navbar-brand" href="<?php echo $baseUrl . '/'; ?>"><img src="<?php echo $basePath; ?>/img/logo.png" alt="Poorapo"/></h1></a>
		  <? }?>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="<? echo $homeActive;?>"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories<span class="caret"></span></a>
			<ul class="dropdown-menu" role="menu"><?php if( isset($categoriesArr) )
					{
						foreach( $categoriesArr as $key=>$currentCategoryData )
						{
							$urlCatName = "";
							$currCatName = trim($currentCategoryData["category_name"]);
							$catNameArr = explode( " ",$currCatName );
							for( $catArrId = 0; $catArrId < count($catNameArr); $catArrId++ )
							{
								if( $catArrId > 0 )
								{
									$urlCatName .= "-";
								}
								$urlCatName .= trim($catNameArr[$catArrId]);
							}
							$catResultsUrl = $baseUrl . "/" . $urlCatName . "-" . $currentCategoryData["category_id"];
						?><li><a href="<?php echo $catResultsUrl; ?>"><?php echo trim($currentCategoryData["category_name"]); ?></a></li><?php }
					}?></ul>
			</li>
			<li class="<? echo $paymentActive;?>"><a href="<?php echo $baseUrl; ?>/cms/Refunds-Payments-13">Payments</a></li>
			<li class="<? echo $contactActive;?>"><a href="<?php echo $baseUrl; ?>/users/contact-us">Contact</a></li>
			<?php if(isset($_SESSION['user'])){?>
			
			<?php if($_SESSION['user']['user_type'] == 4){  ?>
				<li><a href="<?php echo $baseUrl; ?>/admin/dashboard">Admin</a></li>
				<li><a href="<?php echo $baseUrl; ?>/users/logout">Get Out</a></li>
			<?}else{  ?>
				<li class="dropdown"><a  href="javascript:void(0)" data-toggle="dropdown" class="dropdown-toggle"><?php echo $_SESSION['user']['username']; ?><span class="caret"></span></a>
			<ul class="dropdown-menu" role="menu">
			<? if(isset($_SESSION['user'])){
				$base_user_id = base64_encode($_SESSION['user']['user_id']);
			}?>
			<? if(isset($_SESSION['user']['user_type']) && $_SESSION['user']['user_type']=='5'){?>
				 <li><a href="<?php echo $baseUrl; ?>/users/provider-users">Dashboard</a></li>
			<? } ?>
				<li><a href="<?php echo $baseUrl; ?>/users/view-profile?uid=<? echo $base_user_id;?>">View Profile</a></li>
			    <li><a href="<?php echo $baseUrl; ?>/users/change-password">Change Password</a></li>               
                <li><a href="<?php echo $baseUrl; ?>/users/logout">Get Out</a></li>
             </ul>
			</li>
			<?}}else{?>
            <li class="<? echo $loginActive;?>"><a href="<?php echo $baseUrl; ?>/users/login">Get In</a></li>
			<li><a href="<?php echo $baseUrl; ?>/users/register" style="padding:0;margin-top:15px;margin-left:20px;"><span class="btn btn-default">Register</span></a></li>
			<?}?>
		  </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>