<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
	'ZfcAdmin\Mapper\DataTable'                                       => __DIR__ . '/src/ZfcAdmin/Mapper/DataTable.php',
	'ZfcAdmin\View\Helper\ConfigItem'                                 => __DIR__ . '/src/ZfcAdmin/View/Helper/ConfigItem.php',
	'ZfcAdmin\Controller\Plugin\Myplugin'                             => __DIR__ . '/src/ZfcAdmin/Plugin/MyPlugin.php',
	'ZfcAdmin\Controller\Plugin\Adminplugin'         			  => __DIR__ . '/src/ZfcAdmin/Plugin/AdminPlugin.php',

  );
