 <?php if(isset($_SESSION['user']) && $_SESSION['user']['user_type']!=3){?>
 <div class="container">
		<div class="mar_t">
			<div class="row"><?php if( isset($this->menuIssuesArr) && count($this->menuIssuesArr) > 0 )
				{
					foreach( $this->menuIssuesArr as $key=>$currentMIssueData )
					{
					?><div class="col-md-4 columan_divs">
							<div class="panel panel-default">
								<div class="panel-heading"><h3><?php echo trim($currentMIssueData["category_name"]); ?> - <?php echo trim($currentMIssueData["issue_title"]); ?></h3></div>
								<div class="panel-body">
									<div>
									<div class="testimonial">
									<p class="testimonial_f"><?php echo $currentMIssueData["issue_decription"]; ?></p>
									</div>
									<div class="arrow-down"></div>
									<p class="testimonial-author">
									<a href="#" class="btn btn-info btn-xs" data-toggle="modal" data-target="#exampleModal" >Share </a>
									<?php if(isset($_SESSION['user'])){
										if($currentMIssueData["like_value"]==1){
									?>
									<span id="likeStatus<?php echo $key; ?>"><a href="JavaScript:void(0);" class="btn btn-primary btn-xs" onclick="addLikeCount(0,<?php echo $key; ?>,<?php echo $currentMIssueData["issue_id"]; ?>,<?php echo $currentMIssueData["total_likes"]; ?>);">UnLike</a></span>
									<?php }else{?>
									<span id="likeStatus<?php echo $key; ?>"><a href="JavaScript:void(0);" class="btn btn-primary btn-xs" onclick="addLikeCount(1,<?php echo $key; ?>,<?php echo $currentMIssueData["issue_id"]; ?>,<?php echo $currentMIssueData["total_likes"]; ?>);">Like</a></span>
									<?php }}else{?>
									<span id="likeStatus<?php echo $key; ?>"><a href="JavaScript:void(0);" class="btn btn-primary btn-xs" onclick="addLikeCount(2,0,0,0);">Like</a></span>
									<? }?>
									</p>
									<div class="social_count">
									<div id="likeCount<?php echo $key; ?>"><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span><?php echo $currentMIssueData["total_likes"]; ?></div>
									<div><span class="glyphicon glyphicon-share-alt" aria-hidden="true"></span> 20000</div>
									</div>
									
									</div>
								</div>
							</div>
						</div><?php }
				}
				?>
							
				
			</div>
		</div>
    </div> 
<? } else {?>
	<script> window.location=BASE_URL+"/admin/dashboard"; </script>
<? }?>