 <div class="container">
		<div class="mar_t">
			<div class="row">
				<div class="col-md-4 columan_divs">
					<div class="panel panel-default">
						<div class="panel-heading"><h3>Education - syllabus problem</h3></div>
						<div class="panel-body">
							<div>
							<div class="testimonial">
							<p class="testimonial_f">Thanks for the fantastic job done to our site molsons.in. It was a pleasure working with the team as they worked closely with us every step of the way.</p>
							</div>
							<div class="arrow-down"></div>
							<p class="testimonial-author">
							<a href="#" class="btn btn-info btn-xs" data-toggle="modal" data-target="#exampleModal" >Share </a>
							<a href="#" class="btn btn-primary btn-xs">Like</a></p>
							<div class="social_count">
							<div><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>200</div>
							<div><span class="glyphicon glyphicon-share-alt" aria-hidden="true"></span> 20000</div>
							</div>
							
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-4 columan_divs">
					<div class="panel panel-default">
						<div class="panel-heading"><h3>Education - syllabus problem</h3></div>
						<div class="panel-body">
							<div>
							<div class="testimonial">
							<p class="testimonial_f">Thanks for the fantastic job done to our site molsons.in. It was a pleasure working with the team as they worked closely with us every step of the way.</p>
							</div>
							<div class="arrow-down"></div>
							<p class="testimonial-author">
							<a href="#" class="btn btn-info btn-xs">Share </a>	
							<a href="#" class="btn btn-primary btn-xs">Like</a>
							<div class="social_count">
							<div><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>200</div>
							<div><span class="glyphicon glyphicon-share-alt" aria-hidden="true"></span> 20000</div>
							</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-4 columan_divs">
					<div class="panel panel-default">
						<div class="panel-heading"><h3>Education - syllabus problem</h3></div>
						<div class="panel-body">
							<div>
							<div class="testimonial">
							<p class="testimonial_f">Thanks for the fantastic job done to our site molsons.in. It was a pleasure working with the team as they worked closely with us every step of the way.</p>
							</div>
							<div class="arrow-down"></div>
							<p class="testimonial-author">
							<a href="#" class="btn btn-info btn-xs">Share </a>	
							<a href="#" class="btn btn-primary btn-xs">Like</a>	
							<div class="social_count">
							<div><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>200</div>
							<div><span class="glyphicon glyphicon-share-alt" aria-hidden="true"></span> 20000</div>
							</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-4 columan_divs">
					<div class="panel panel-default">
						<div class="panel-heading"><h3>Education - syllabus problem</h3></div>
						<div class="panel-body">
							<div>
							<div class="testimonial">
							<p class="testimonial_f">Thanks for the fantastic job done to our site molsons.in. It was a pleasure working with the team as they worked closely with us every step of the way.</p>
							</div>
							<div class="arrow-down"></div>
							<p class="testimonial-author">
							<a href="#" class="btn btn-info btn-xs">Share </a>	
							<a href="#" class="btn btn-primary btn-xs">Like</a>
							<div class="social_count">
							<div><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>200</div>
							<div><span class="glyphicon glyphicon-share-alt" aria-hidden="true"></span> 20000</div>
							</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-4 columan_divs">
					<div class="panel panel-default">
						<div class="panel-heading"><h3>Education - syllabus problem</h3></div>
						<div class="panel-body">
							<div>
							<div class="testimonial">
							<p class="testimonial_f">Thanks for the fantastic job done to our site molsons.in. It was a pleasure working with the team as they worked closely with us every step of the way.</p>
							</div>
							<div class="arrow-down"></div>
							<p class="testimonial-author">
							<a href="#" class="btn btn-info btn-xs">Share </a>
							<a href="#" class="btn btn-primary btn-xs">Like</a>
							<div class="social_count">
							<div><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>200</div>
							<div><span class="glyphicon glyphicon-share-alt" aria-hidden="true"></span> 20000</div>
							</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-4 columan_divs">
					<div class="panel panel-default">
						<div class="panel-heading"><h3>Education - syllabus problem</h3></div>
						<div class="panel-body">
							<div>
							<div class="testimonial">
							<p class="testimonial_f">Thanks for the fantastic job done to our site molsons.in. It was a pleasure working with the team as they worked closely with us every step of the way.</p>
							</div>
							<div class="arrow-down"></div>
							<p class="testimonial-author">
							<a href="#" class="btn btn-info btn-xs">Share </a>	
							<a href="#" class="btn btn-primary btn-xs">Like</a>
							<div class="social_count">
							<div><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>200</div>
							<div><span class="glyphicon glyphicon-share-alt" aria-hidden="true"></span> 20000</div>
							</div>
							</div>
						</div>
					</div>
				</div><div class="col-md-4 columan_divs">
					<div class="panel panel-default">
						<div class="panel-heading"><h3>Education - syllabus problem</h3></div>
						<div class="panel-body">
							<div>
							<div class="testimonial">
							<p class="testimonial_f">Thanks for the fantastic job done to our site molsons.in. It was a pleasure working with the team as they worked closely with us every step of the way.</p>
							</div>
							<div class="arrow-down"></div>
							<p class="testimonial-author">
							<a href="#" class="btn btn-info btn-xs">Share </a>		
							<a href="#" class="btn btn-primary btn-xs">Like</a>
							<div class="social_count">
							<div><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>200</div>
							<div><span class="glyphicon glyphicon-share-alt" aria-hidden="true"></span> 20000</div>
							</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-4 columan_divs">
					<div class="panel panel-default">
						<div class="panel-heading"><h3>Education - syllabus problem problem</h3></div>
						<div class="panel-body">
							<div>
							<div class="testimonial">
							<p class="testimonial_f">Thanks for the fantastic job done to our site molsons.in. It was a pleasure working with the team as they worked closely with us every step of the way.</p>
							</div>
							<div class="arrow-down"></div>
							<p class="testimonial-author">
							<a href="#" class="btn btn-info btn-xs" data-toggle="modal" data-target=".bs-example-modal-lg">Share </a>	
							<a href="#" class="btn btn-primary btn-xs">Like</a>
							<div class="social_count">
							<div><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>200</div>
							<div><span class="glyphicon glyphicon-share-alt" aria-hidden="true"></span> 20000</div>
							</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-4 columan_divs">
					<div class="panel panel-default">
						<div class="panel-heading"><h3>Education - syllabus problem problem</h3></div>
						<div class="panel-body">
							<div>
							<div class="testimonial">
							<p class="testimonial_f">Thanks for the fantastic job done to our site molsons.in. It was a pleasure working with the team as they worked closely with us every step of the way.</p>
							</div>
							<div class="arrow-down"></div>
							<p class="testimonial-author">
							<a href="#" class="btn btn-info btn-xs" data-toggle="modal" data-target=".bs-example-modal-lg">Share </a>	
							<a href="#" class="btn btn-primary btn-xs">Like</a>
							<div class="social_count">
							<div><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>200</div>
							<div><span class="glyphicon glyphicon-share-alt" aria-hidden="true"></span> 20000</div>
							</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
    </div> 