<div class="container page_heading min_height">
	<div class="mar_t page-header pad_0">
		<h1 id="forms">Our Heading</h1>
	</div>
	<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
	<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
	<div class=""  style="width:280px; margin:0 auto;">
          <form id="check_form" class="form col-md-12 center-block" method="POST">
			<div class="form-group">
              <input type="text" class="form-control" id="srch_num" name="srch_num" placeholder="Search Number" style="width:150px !important;float:left;">&nbsp;&nbsp;
			  <button type="button" class="btn btn-primary" onclick="javascript:void('0');" style="width:auto !important;margin-left:2% !important;float:left;">Submit</button>
			  <div class="clearfix"></div>
            </div>		
		</form>
	</div>
	 <div class="clearfix"></div>
	<div class="tab_w">
		<table class="table table-striped table-hover">
			  <thead>
					<tr>
					  <th>#</th>
					  <th>Column heading</th>
					  <th>Column heading</th>
					</tr>
			  </thead>
			  <tbody>
					<tr>
					  <td>1</td>
					  <td>Column content</td>
					  <td>Column content</td>
					</tr>
					<tr>
					  <td>2</td>
					  <td>Column content</td>
					  <td>Column content</td>
					</tr>
			</tbody>
		</table>
	</div>
</div>