 <div class="container">

  <div id="loginModal" class="show" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <h1 class="text-center">Change Password to Poorapo</h1>
      </div>
      <div class="modal-body">
          <form id="changePasswordForm" class="form col-md-12 center-block" method="POST">
			<div class="form-group">
              <input type="password" class="form-control input-lg" id="oldPassword" name="oldPassword" placeholder="Old Password">
            </div>
			<div class="form-group">
              <input type="password" class="form-control input-lg" id="newPassword" name="newPassword" placeholder="New Password">
            </div><div class="form-group">
              <input type="password" class="form-control input-lg"  id="confirmPassword" name="confirmPassword" placeholder="Confirm Password">
            </div>
            <div class="form-group">
              <button id="submit" class="btn btn-primary btn-lg btn-block" onclick="return changePassword();">Save</button>&nbsp;&nbsp;&nbsp;<span id="reload"></span>
            </div>
          </form>
      </div><div class="clearfix"></div>
  </div>
  </div>
</div>