<div class="container min_height">	
  <div id="loginModal" class="show"  role="dialog" aria-hidden="true">
  <div class="modal-dialog">
	<?php if(isset($this->output) && $this->output=='success'){?>
	<div class="alert alert-dismissible alert-success">
		<button type="button" class="close" data-dismiss="alert">×</button>
		<strong>Sent Successfully</strong>
	</div>
	<?}?>
  <div class="modal-content">
      <div class="modal-header">
          <h1 class="text-center">Contact Us</h1>
      </div>
      <div class="modal-body">
          <form id="con_form_id" class="form col-md-12 center-block" method="POST">
			<div class="form-group">
              <input type="text" class="form-control" id="firstName" name="firstName" placeholder="First Name">
			  <span id="fnameError" style="color:red"></span>
            </div>
			<div class="form-group">
              <input type="text" class="form-control" id="lastName" name="lastName" placeholder="Last Name">
            </div>
			<div class="form-group">
              <input type="text" class="form-control"  id="contactEmail" name="contactEmail" placeholder="Contact Email">
			  <span id="emailError" style="color:red"></span>
            </div>
			<div class="form-group">
              <input type="text" class="form-control"  id="mobileNumber" name="mobileNumber" placeholder="Mobile Number">
            </div>
			<div class="form-group">
              <textarea id="contactMessage" class="form-control"  name="contactMessage" placeholder="Conatct Message"></textarea>
			 <span id="messageError" style="color:red"></span>
            </div>
            <div class="form-group">
              <button type="button" class="btn btn-primary  btn-block" onclick="contactFormFunction()">Submit</button>
            </div>
          </form>
      </div><div class="clearfix"></div>
  </div>
  </div>
</div>
</div>
<script>
function contactFormFunction(){
	var flag=true;
	var fname=$('#firstName').val();
	var lnmae=$('#lastName').val();
	var contactemail=$('#contactEmail').val();
	var mobile=$('#mobileNumber').val();
	var message=$('#contactMessage').val();
	if(fname==""){
		$('#fnameError').html('Required');
		flag==false;
	}else{
		$('#fnameError').html('');
	}
	if(contactemail==''){
		$('#emailError').html('Required');
		flag=false;
	}else if(checkEmail(contactemail)==false){
		$('#emailError').html('Invalid Email');
		flag=false;
	}else{
		$('#emailError').html('');
	}
	if(message==""){
		$('#messageError').html('Required');
		flag==false;
	}else{
		$('#messageError').html('');
	}
	if(flag==true){
		$('#con_form_id').submit();
	}
}
</script>