	<div class="container reg_w_12 min_height">
	<div class="panel panel panel-default mar_t">
		<div class="panel-heading reg_bg">
			<h3 class="panel-title">View Profile</h3>
			<div class="view_profile_r"><a href="#">Edit Profile</a></div>
		</div> 
		<div class="panel-body">
			<div class="panel panel-default">
				<div class="panel-heading" id="tab_1" onclick="regTab1(1)">Login Deatils
				<i id="icon1" class="glyphicon glyphicon-triangle-top  pull-right"></i></div>
				<div class="panel-body" id="tab_1_hide">
				<form class="form-horizontal">
				<div class="form-group">
				<label for="inputtype" class="col-sm-3 control-label">User Type :</label>
				<div class="col-sm-8">
					<p class="form-control-static">Employee</p>
				</div>
				</div>
				<div class="form-group">
				<label for="inputEmail3" class="col-sm-3 control-label">Email :</label>
				<div class="col-sm-8">
				<p class="form-control-static">info@aapthitech.com</p>
				</div>
				</div>
				<div class="form-group">
				<label for="inputPassword3" class="col-sm-3 control-label">Password :</label>
				<div class="col-sm-8">
				<p class="form-control-static">**********</p>
				</div>
				</div>
				</form>
				</div>
			</div>
			<div class="panel panel-default">
				<div class="panel-heading" onclick="regTab1(2)">Personal Information 
				<i  id="icon2"class="glyphicon glyphicon-triangle-bottom  pull-right"></i></div>
				<div class="panel-body" id="tab_2_hide" style="display:none;">
				<form class="form-horizontal">
				<div class="form-group">
				<label for="inputfname" class="col-sm-3 control-label">First Name</label>
				<div class="col-sm-8">
					<p class="form-control-static">xxxxxxxxxxx</p>
				</div>
				</div>
				<div class="form-group">
				<label for="inputlname" class="col-sm-3 control-label">Last Name</label>
				<div class="col-sm-8">
					<p class="form-control-static">xxxxxxxxxxx</p>
				</div>
				</div>
				<div class="form-group">
				<label class="col-sm-3 control-label">Gender</label>
				<div class="col-sm-8">
					<p class="form-control-static">male</p>
				</div>
				</div>
				<div class="form-group">
				<label for="inputEmail3" class="col-sm-3 control-label">Date of Birth</label>
				<div class="col-sm-3">
					<p class="form-control-static">10/08/1988</p>
				</div>
				</div>
				<div class="form-group">
				<label for="inputPassword3" class="col-sm-3 control-label">Country</label>
				<div class="col-sm-8">
				<p class="form-control-static">India</p>
				</div>
				</div>	
				<div class="form-group">
				<label for="inputpname" class="col-sm-3 control-label">Mobile Number</label>
				<div class="col-sm-8">
					<p class="form-control-static">+91 9908085654</p>
				</div>
				</div>	
				<div id="hideemployeeDiv">				
				<div class="form-group">
				<label for="inputpname" class="col-sm-3 control-label">Parent First Name</label>
				<div class="col-sm-8">
					<p class="form-control-static">xxxxxxxxxxx</p>
				</div>
				</div>
				<div class="form-group">
				<label for="inputplname" class="col-sm-3 control-label">Parent Last Name</label>
				<div class="col-sm-8">
					<p class="form-control-static">xxxxxxxxxxx</p>
				</div>
				</div>
				<div class="form-group">
				<label for="inputpnm" class="col-sm-3 control-label">Parent Mobile Number</label>
				<div class="col-sm-8">
					<p class="form-control-static">+91 9908669986</p>
				</div>
				</div>
				<div class="form-group">
				<label for="inputpem" class="col-sm-3 control-label">Parent Email</label>
				<div class="col-sm-8">
					<p class="form-control-static">infoparent@gmal.com</p>
				</div>
				</div>
				<div class="form-group">
				<label for="inputppin" class="col-sm-3 control-label">Parent Pincode</label>
				<div class="col-sm-8">
					<p class="form-control-static">************</p>
				</div>
				</div>
				<div class="form-group">
				<label for="inputafi" class="col-sm-3 control-label">Annual Family Income</label>
				<div class="col-sm-8">
					<p class="form-control-static">20,0000</p>
				</div>
				</div>
				<div class="form-group">
				<label for="inputfn" class="col-sm-3 control-label"> Family Network</label>
				<div class="col-sm-8">
					<p class="form-control-static">10</p>
				</div>
				</div>
				</div>
				<div id="employeeDiv">
				<div class="form-group">
				<label for="inputectc" class="col-sm-3 control-label">Employee CTC</label>
				<div class="col-sm-8">
					<p class="form-control-static">50,000</p>
				</div>
				</div>
				</div>
				</form>
				</div>
			</div>
			<div class="panel panel-default">
				<div class="panel-heading" onclick="regTab1(3)">12th Class College Information 
				<i  id="icon3"class="glyphicon glyphicon-triangle-bottom  pull-right"></i></div>
				<div class="panel-body" id="tab_3_hide" style="display:none;">
				<form class="form-horizontal">
				<div class="form-group">
				<label for="inputPassword3" class="col-sm-3 control-label">State</label>
				<div class="col-sm-8">
				<select class="form-control" id="select">
				<option>Select State</option>
				<option>2</option>
				<option>3</option>
				<option>4</option>
				<option>5</option>
				</select>
				</div>
				</div>
				<div class="form-group">
				<label for="inputPassword3" class="col-sm-3 control-label">Deistic</label>
				<div class="col-sm-8">
				<select class="form-control" id="select">
				<option>Select Deistic</option>
				<option>2</option>
				<option>3</option>
				<option>4</option>
				<option>5</option>
				</select>
				</div>
				</div>
				<div class="form-group">
				<label for="inputcname" class="col-sm-3 control-label">College Name</label>
				<div class="col-sm-8">
				<input type="text" class="form-control" id="inputcname" placeholder="College Name">
				</div>
				</div>
				<div class="form-group">
				<label for="inputpname" class="col-sm-3 control-label">Principal Name</label>
				<div class="col-sm-8">
				<input type="text" class="form-control" id="inputpname" placeholder="Principal Name">
				</div>
				</div>
				<div class="form-group">
				<label for="inputpnmb" class="col-sm-3 control-label">Principal Mobile Number</label>
				<div class="col-sm-8">
				<input type="text" class="form-control" id="inputpnmb" placeholder="Principal Mobile Number">
				</div>
				</div>
				<div class="form-group">
				<label for="inputpemail" class="col-sm-3 control-label">Principal Email</label>
				<div class="col-sm-8">
				<input type="text" class="form-control" id="inputpemail" placeholder="Principal Email">
				</div>
				</div>
				</form>
				</div>
			</div>
			<div class="panel panel-default">
				<div class="panel-heading" onclick="regTab1(4)">Entrance Exam Information
				<i  id="icon4"class="glyphicon glyphicon-triangle-bottom  pull-right"></i></div>
				<div class="panel-body" id="tab_4_hide" style="display:none;">
					<div class="form-horizontal">
						<div class="form-group">
							<div class="col-sm-3">
								<label class="control-label" for="focusedInput">Year</label>
								<select class="form-control" id="select">
								<option>Select Year</option>
								<option>2</option>
								<option>3</option>
								<option>4</option>
								<option>5</option>
								</select>
							</div>
						
							<div class="col-sm-3">
								<label class="control-label" for="focusedInput">Exam Name</label>
								<input class="form-control" id="focusedInput" type="text" value="" placeholder="Exam Name">
							</div>
							<div class="col-sm-3">
								<label class="control-label" for="focusedInput">Exam Rank</label>
								<input class="form-control" id="focusedInput" type="text" value="" placeholder="Exam Rank">
							</div>
							<div class="col-sm-3">
								<label class="control-label" for="focusedInput">&nbsp;</label><br/>
								<button type="submit" class="btn btn-primary ">Add Another</button>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="panel panel-default">
				<div class="panel-heading" onclick="regTab1(5)">Under Graduation Information
				<i  id="icon5"class="glyphicon glyphicon-triangle-bottom  pull-right"></i></div>
				<div class="panel-body" id="tab_5_hide" style="display:none;">
				<div class="form-horizontal">
					<div class="form-group">
						<label for="select" class="col-sm-3 control-label">Degree</label>
						<div class="col-sm-8">
							<select class="form-control" id="select">
							<option>BA</option>
							<option>BE/B.TECH</option>
							<option>BSC</option>
							<option>BCOM</option>
							<option>BCA</option>
							</select>
						</div>
					</div>
					<div class="form-group">
						<label for="select" class="col-sm-3 control-label">University</label>
						<div class="col-sm-8">
							<select class="form-control" id="select">
							<option>Osmania University</option>
							<option>Jawaharlal University</option>
							<option>Andhra Pradesh Open University</option>
							<option>University Hyderabad</option>
							<option>Nagarjuna University</option>
							</select>
						</div>
					</div>
					<div class="form-group">
						<label for="select" class="col-sm-3 control-label">College</label>
						<div class="col-sm-8">
							<select class="form-control" id="select">
							<option>CVSR College</option>
							<option>Muffakham Jah College</option>
							<option>Deccan College</option>
							<option>Vasavi College </option>
							<option>K.S.Raju College</option>
							</select>
						</div>
					</div>
					<div class="form-group">
						<label for="select" class="col-sm-3 control-label">Specialization</label>
						<div class="col-sm-8">
							<select class="form-control" id="select">
							<option>CVSR College</option>
							<option>Muffakham Jah College</option>
							<option>Deccan College</option>
							<option>Vasavi College </option>
							<option>K.S.Raju College</option>
							</select>
						</div>
					</div>
					<div class="form-group">
						<label for="select" class="col-sm-3 control-label">Year</label>
						<div class="col-sm-8">
							<select class="form-control" id="select">
							<option>1988</option>
							<option>1989</option>
							<option>1990</option>
							<option>1991</option>
							<option>1992</option>
							</select>
						</div>
					</div>
				</div>
			</div>
			</div>
			<div class="panel panel-default">
				<div class="panel-heading" onclick="regTab1(6)">Post Graduation Information
				<i  id="icon5"class="glyphicon glyphicon-triangle-bottom  pull-right"></i></div>
				<div class="panel-body" id="tab_6_hide" style="display:none;">
					<div class="form-horizontal">
					<div class="form-group">
						<label for="select" class="col-sm-3 control-label">Master Degree</label>
						<div class="col-sm-8">
							<select class="form-control" id="select">
							<option>BA</option>
							<option>BE/B.TECH</option>
							<option>BSC</option>
							<option>BCOM</option>
							<option>BCA</option>
							</select>
						</div>
					</div>
					<div class="form-group">
						<label for="select" class="col-sm-3 control-label">Master University</label>
						<div class="col-sm-8">
							<select class="form-control" id="select">
							<option>Osmania University</option>
							<option>Jawaharlal University</option>
							<option>Andhra Pradesh Open University</option>
							<option>University Hyderabad</option>
							<option>Nagarjuna University</option>
							</select>
						</div>
					</div>
					<div class="form-group">
						<label for="select" class="col-sm-3 control-label">College</label>
						<div class="col-sm-8">
							<select class="form-control" id="select">
							<option>CVSR College</option>
							<option>Muffakham Jah College</option>
							<option>Deccan College</option>
							<option>Vasavi College </option>
							<option>K.S.Raju College</option>
							</select>
						</div>
					</div>
					<div class="form-group">
						<label for="select" class="col-sm-3 control-label">Specialization</label>
						<div class="col-sm-8">
							<select class="form-control" id="select">
							<option>CVSR College</option>
							<option>Muffakham Jah College</option>
							<option>Deccan College</option>
							<option>Vasavi College </option>
							<option>K.S.Raju College</option>
							</select>
						</div>
					</div>
					<div class="form-group">
						<label for="select" class="col-sm-3 control-label">Year</label>
						<div class="col-sm-8">
							<select class="form-control" id="select">
							<option>1988</option>
							<option>1989</option>
							<option>1990</option>
							<option>1991</option>
							<option>1992</option>
							</select>
						</div>
					</div>
				</div>
				</div>
			</div>
			<div class="panel panel-default">
				<div class="panel-heading" onclick="regTab1(7)">Doctorate Information
				<i  id="icon5"class="glyphicon glyphicon-triangle-bottom  pull-right"></i></div>
				<div class="panel-body" id="tab_7_hide" style="display:none;">
					<div class="form-horizontal">
						<div class="form-group">
						<label for="inputcname" class="col-sm-3 control-label">PHD</label>
						<div class="col-sm-8">
						<input type="text" class="form-control" id="inputcname" placeholder="PHD">
						</div>
						</div>
					</div>
				</div>
			</div>
		</div> 
		<input type="hidden" id="opentabId" value="1">
	</div>
</div>

<script> 
function regTab1(tabid){
var closeTadId=$('#opentabId').val();
$("#tab_"+closeTadId+"_hide").slideUp("slow");
$("#icon"+closeTadId).removeClass("glyphicon-triangle-top").addClass("glyphicon-triangle-bottom");
$("#tab_"+tabid+"_hide").slideDown("slow");
$("#icon"+tabid).removeClass("glyphicon-triangle-bottom").addClass("glyphicon-triangle-top");
$('#opentabId').val(tabid);
}
</script>