<div class="container">

  <div id="loginModal" class="show" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <h1 class="text-center">Forget Password to Poraapo</h1>
      </div>
      <div class="modal-body">
          <form id="forgetForm" class="form col-md-12 center-block" method="POST">
			<div class="form-group">
              <input type="text" id="forgetMail" name="forgetMail"  class="form-control input-lg" placeholder="Email">
            </div>
            <div class="form-group">
              <button id="button" class="btn btn-primary  btn-block" onclick="forgetPassword();">Submit</button>
            </div>
          </form>
      </div><div class="clearfix"></div>
  </div>
  </div>
</div>
</div>
