 <div class="container">

  <div id="loginModal" class="show" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <!--<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>-->
          <h1 class="text-center">Forget Password to Poorapo</h1>
      </div>
      <div class="modal-body">
          <form id="forgetForm" class="form col-md-12 center-block" method="POST">
			<div class="form-group">
              <input type="text" id="forgetMail" name="forgetMail"  class="form-control input-lg" placeholder="Email">
            </div>
            <div class="form-group">
              <button id="submit" class="btn btn-primary btn-lg btn-block" onclick="forgetPassword();">Submit</button>&nbsp;&nbsp;&nbsp;<span id="reload"></span>
            </div>
            </div>
          </form>
      </div><div class="clearfix"></div>
  </div>
  </div>
</div>