<div class="container min_height">

  <div id="loginModal" class="show" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="alert alert-dismissible alert-success" style="display:none" id="sucessdiv">
		<strong id="sucessMsg"></strong>
</div>
<div class="alert alert-dismissible alert-danger" style="display:none" id="errordiv">
		<strong id="errorMsg"></strong>
	</div>
  <div class="modal-content">
      <div class="modal-header">
          <h1 class="text-center">Forget Password</h1>
      </div>
      <div class="modal-body">
		  <span id="errorMsg" style="color:red"></span>
          <form id="forgetForm" class="form col-md-12 center-block" method="POST">
			<div class="form-group">
              <input type="text" id="forgetMail" name="forgetMail"  class="form-control" placeholder="Email">
			  <span id="emailError" style="color:red"></span>
            </div>
            <div class="form-group">
              <button type="button" id="submit" class="btn btn-primary  btn-block" onclick="forgetPassword();">Submit</button>
			  <center><span id="reload"></span></center>
            </div>
          </form>
      </div><div class="clearfix"></div>
  </div>
  </div>
</div>
</div>
<script>
$('#forgetMail').keypress(function(e){
	if( e.keyCode == 13 ){
		forgetPassword();
	}
});
</script>
