<?
	if(isset($_SESSION['user']['user_type_id']) && $_SESSION['user']['user_type_id']=='4'){?>
	<script>
		window.location = BASE_URL+'/admin/dashboard';
	</script>
   <? } else if(isset($_SESSION['user']['user_type_id']) && $_SESSION['user']['user_type_id']=='1'){?>
	<script>
		window.location = BASE_URL;
	</script>
  <? } else if(isset($_SESSION['user']['user_type_id']) && $_SESSION['user']['user_type_id']=='2'){?>
	<script>
		window.location = BASE_URL;
	</script>
 <? }else if(isset($_SESSION['user']['user_type_id']) && $_SESSION['user']['user_type_id']=='3'){?>
	<script>
		window.location = BASE_URL;
	</script>
<? } else { ?>
 <?php 
	$header=$this->action('Application\Controller\IndexController', 'headerAction',array('20','10'));
	$baseUrl = $header->headerarray['baseUrl'];
	$basePath = $header->headerarray['basePath'];
?>
 <div class="container">

  <div id="loginModal" class="show"  role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <!--<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>-->
          <h1 class="text-center">Get In to Poraapo</h1>
      </div>
      <div class="modal-body">
          <form id="loginForm" class="form col-md-12 center-block" method="POST">
            <div class="form-group">
              <input type="text" class="form-control" id="email" name="email" placeholder="Email">
			  <span id="emailError" style="color:red"></span>
            </div>
            <div class="form-group">
              <input type="password" class="form-control" id="password" name="password" placeholder="Password">
			  <span id="passwordError" style="color:red"></span>
            </div>
			<span id="errorMsg" style="color:red"></span>
            <div class="form-group">
              <button type="button" class="btn btn-primary btn-block" onclick="loginValidations();">Sign In</button>
			  <center><span id="reload"></span></center>
            </div>
			<div class="form-group">
				<span>Don't have an account <a href="<?php echo $baseUrl;?>/users/register" class="undeline">Register here</a></span>
				<span class="pull-right"><a href="<?php echo $baseUrl;?>/users/forgot-password" class="undeline">Forgot Password?</a></span>
			</div>
          </form>
      </div><div class="clearfix"></div>
  </div>
  </div>
</div>

    </div> <!-- /container -->
<script>
$('#password').keypress(function(e){
	if( e.keyCode == 13 ){
		loginValidations();
	}
});
</script>
<? } ?>