<div class="container min_height">	
  <div id="loginModal" class="show"  role="dialog" aria-hidden="true">
  <div class="modal-dialog">
	<?php 	
		$txnid = substr(hash('sha256', mt_rand() . microtime()), 0, 20);
	?>
  <div class="modal-content">
      <div class="modal-header">
          <h1 class="text-center">Payment Form</h1>
      </div>
      <div class="modal-body">
          <form id="con_form_id" class="form col-md-12 center-block" method="POST">
			<div class="form-group">
              <input type="text" class="form-control" id="firstname" name="firstname" placeholder="User Name" value="<? if(isset($_SESSION['user']['user_id']) && $_SESSION['user']['user_id']!=""){ echo $_SESSION['user']['username'];}?>">
			  <span id="fnameError" style="color:red"></span>
            </div>			
			<div class="form-group">
              <input type="text" class="form-control"  id="email" name="email" placeholder="Email Id" value="<? if(isset($_SESSION['user']['user_id']) && $_SESSION['user']['user_id']!=""){ echo $_SESSION['user']['email'];}?>">
			  <span id="emailError" style="color:red"></span>
            </div>
			<div class="form-group">
              <input type="text" class="form-control"  id="phone" name="phone" placeholder="Mobile Number" value="">
			  <span id="phnError" style="color:red"></span>
            </div>
			<div class="form-group">
              <input type="text" class="form-control"  id="amount" name="amount" placeholder="Amount" value="">
			  <span id="amtError" style="color:red"></span>
            </div>	
			<input type="hidden" name="txnid" value="<?php echo $txnid; ?>"> 
            <div class="form-group">
              <button type="button" class="btn btn-primary  btn-block" onclick="contactFormFunction()">Submit</button>
            </div>
          </form>
      </div><div class="clearfix"></div>
  </div>
  </div>
</div>
</div>
<script>
function contactFormFunction(){
	var flag=true;
	var fname=$('#firstname').val();
	var amt=$('#amount').val();
	var contactemail=$('#email').val();
	var mobile=$('#phone').val();
	if(fname==""){
		$('#fnameError').html('Required');
		flag==false;
	}else{
		$('#fnameError').html('');
	}	
	if(contactemail==''){
		$('#emailError').html('Required');
		flag=false;
	}else if(checkEmail(contactemail)==false){
		$('#emailError').html('Invalid Email');
		flag=false;
	}else{
		$('#emailError').html('');
	}
	if(amt==""){
		$('#amtError').html('Required');
		flag==false;
	}else{
		$('#amtError').html('');
	}
	if(flag==true){
		$('#con_form_id').submit();
	}
}
</script>