<? if(isset($_GET['uid'])) {?>
	<script>
		setAllTrue();
	</script>
<?}?>
<div class="container reg_w_12 min_height">
	<div class="panel panel panel-default mar_t">
		<div class="panel-heading reg_bg">
		<? if(isset($_SESSION['user']['user_id']) && $_SESSION['user']['user_id']!=""){?>
			<h3 class="panel-title">Edit Profile</h3>
		<?} else {?>
			<h3 class="panel-title">Register with Poraapo</h3>
		<? } ?>
		</div>  
		<? $details=''; if(count($this->userDetails)){ foreach($this->userDetails as $detailss){ $details=$detailss;}}
			$dobex=''; if(isset($details->date_of_birth) && $details->date_of_birth!='') {
				$dob = $details->date_of_birth;
				$dobex = explode("/",$dob);
			}		
		?>
<form  id="frm_meth" name="frm_meth" method="post" action="">	
	<div class="panel-body">
	<div class="panel panel-default">
		<div class="panel-heading" id="tab_1" onclick="regTab1(1,0)">Login Deatils
			<i id="icon1" class="glyphicon glyphicon-triangle-top  pull-right"></i>
		</div>
		<div class="panel-body" id="tab_1_hide">
			<div class="form-horizontal">
				<div class="form-group">
					<label for="inputtype" class="col-sm-3 control-label">User Type</label>
					<div class="col-sm-8">
						<span class="error_msg_disp" id="user_type_req"></span>
						<select class="form-control" id="user_type" name="user_type" onChange="return switchinUser();">
							<option value=''>Select User Type</option>
							<? if(count($usertypes)!='') {
							foreach($usertypes as $user_type){ if($user_type->user_type_id!=4) { if($details->user_type_id == $user_type->user_type_id){?>
								<option value="<? echo $user_type->user_type_id?>" selected="selected"><? echo ucfirst($user_type->user_type_name);?></option>
							<?} else{?>
								<option value="<? echo $user_type->user_type_id?>"><? echo ucfirst($user_type->user_type_name);?></option>
							<?} }}}?>
						</select>
					</div>
				</div>
				
				<div class="form-group">
					<label for="inputfname" class="col-sm-3 control-label">First Name</label>
					<div class="col-sm-8">
					<span class="error_msg_disp" id="user_firstname_req"></span>
						<input type="text" class="form-control" id="user_first_name" placeholder="First Name" name="user_first_name" value="<? if(isset($details->first_name) && $details->first_name!='') {echo ucfirst($details->first_name);}else{}?>">
					</div>
				</div>
				<div class="form-group">
					<label for="inputEmail3" class="col-sm-3 control-label">Email</label>
					<div class="col-sm-8">
						<span class="error_msg_disp" id="user_email_req"></span>
						<input type="email" class="form-control" id="user_email" placeholder="Email" name="user_email" value="<? if(isset($details->email_id) && $details->email_id!='') {echo $details->email_id;}else{}?>" <? if(isset($details->email_id) && $details->email_id!='') {?> readonly="readonly" <?}else{?> onmouseout="return checkEmailVaild();"<? } ?>>
					</div>
				</div>
				<input type="hidden" id="hidCheckValue" name="hidCheckValue" value='0'>
				<? if($details==""){?>
				<div class="form-group">
					<label for="inputPassword3" class="col-sm-3 control-label">Password</label>
					<div class="col-sm-8">
						<span class="error_msg_disp" id="user_pwd_req"></span>
						<input type="password" class="form-control" id="user_password" name="user_password" value="" placeholder="Password">
					</div>
				</div>
				<? } ?>
				<div class="form-group">
					<div class="col-sm-8 col-lg-offset-3">
						<!--<button type="reset" class="btn btn-default">Cancel</button>-->
						<button type="button" class="btn btn-primary " onClick="validateReg(1);">Continue</button>
					</div>
				</div>
			</div>
		</div>
	</div>
	<input type="hidden" id="hid_tab_1" name="hid_tab_1" value="0">
	<div class="panel panel-default">
				<div class="panel-heading" onclick="regTab1(2,0)">Personal Details 
					<i  id="icon2"class="glyphicon glyphicon-triangle-bottom  pull-right"></i>
				</div>
			<div class="panel-body" id="tab_2_hide" style="display:none;">
			<div class="form-horizontal">
					<div class="form-group">
						<label for="inputlname" class="col-sm-3 control-label">Last Name</label>
						<div class="col-sm-8">
							<span class="error_msg_disp" id="user_lastname_req"></span>
							<input type="text" class="form-control" id="user_last_name" name="user_last_name" placeholder="Last Name" value="<? if(isset($details->last_name) && $details->last_name!='') {echo ucfirst($details->last_name);}else{}?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-3 control-label">Gender</label>
						<div class="col-sm-8">
							<span class="error_msg_disp" id="user_gender_req"></span>
							<div class="radio">
								<label>
								<? if(isset($details->gender) && $details->gender=='Male') {?>
									<input type="radio" name="user_gendermf" id="user_gendermf" checked="checked" value="Male">
								<? } else{?>
									<input type="radio" name="user_gendermf" id="user_gendermf" value="Male">
								<? } ?>
									Male
								</label>
								&nbsp;<label>
								<? if(isset($details->gender) && $details->gender=='Female') {?>
									<input type="radio" name="user_gendermf" checked="checked" id="user_gendermf" value="Female">
								<? } else{?>
									<input type="radio" name="user_gendermf"  id="user_gendermf" value="Female">
								<? } ?>
									Female
								</label>
							</div>
						</div>
					</div>
					
				<div class="form-group">
					<label for="inputEmail3" class="col-sm-3 control-label">Date of Birth</label>
					<div class="col-sm-2">
						<!--<select class="form-control" id="user_date" name="user_date">
							<option value="">Date</option>
							<?// $i=1;for($i=1;$i<=31;$i++){ if( $dobex['0'] == $i){?>
								<option value="<? //echo $i;?>" selected="selected"><? //echo $i;?></option>
								<? //} else{?>
									<option value="<?//echo $i;?>"><? //echo $i;?></option>
								<? //} ?>
							<?//}?>
						</select>-->
						<input type="text" class="form-control" id="user_date" name="user_date" placeholder="Date of Birth">
					</div>
					<div class="col-sm-3">
						<select class="form-control" id="user_month" name="user_month">
							<option value="">Month</option>
							<?  $jan='Jan'; $feb='Feb'; $mar='Mar'; $april="Apr"; $may="May"; $june="June"; $july="July"; 
							$aug="Aug"; $sept="Sept"; $oct="Oct"; $nov="Nov"; $dec="Dec";
							$i=1;for($i=1;$i<=12;$i++){ if( $dobex['1'] == $i){?>
									<option value="<? echo $i;?>" selected="selected">
										<?	if($i=='1'){echo $jan;} else if($i=='2'){ echo $feb;}
											else if($i=='3'){ echo $mar;}else if($i=='4'){ echo $april;}
											else if($i=='5'){ echo $may;}else if($i=='6'){ echo $june;}
											else if($i=='7'){ echo $july;}else if($i=='8'){ echo $aug;}
											else if($i=='9'){ echo $sept;}else if($i=='10'){ echo $oct;}
											else if($i=='11'){ echo $nov;}else if($i=='12'){ echo $dec;}
										?>
									</option>
								<? } else{?>
									<option value="<? echo $i;?>">
										<?	if($i=='1'){echo $jan;} else if($i=='2'){ echo $feb;}
											else if($i=='3'){ echo $mar;}else if($i=='4'){ echo $april;}
											else if($i=='5'){ echo $may;}else if($i=='6'){ echo $june;}
											else if($i=='7'){ echo $july;}else if($i=='8'){ echo $aug;}
											else if($i=='9'){ echo $sept;}else if($i=='10'){ echo $oct;}
											else if($i=='11'){ echo $nov;}else if($i=='12'){ echo $dec;}
										?>
									</option>
								<? } ?>
							<?}?>
						</select>
					</div>
					<div class="col-sm-3">
					<span class="error_msg_disp" id="user_dob_req"></span>
						<!--<select class="form-control" id="user_year" name="user_year">
							<option value="">Year</option>
							<?// $i=1;for($i=1960;$i<=2015;$i++){ if( $dobex['2'] == $i){?>
								<option value="<? //echo $i;?>" selected="selected"><? //echo $i;?></option>
							<? //} else{?>
								<option value="<? //echo $i;?>"><? //echo $i;?></option>
							<? //} ?>
							<?//}?>
						</select>-->
						<input type="text" class="form-control" id="user_year" name="user_year" placeholder="Year of Birth">
					</div>
				</div>
				<div class="form-group">
					<label for="inputPassword3" class="col-sm-3 control-label">Country of Birth</label>
					<div class="col-sm-8">
						<span class="error_msg_disp" id="user_country_req"></span>
						<!--<select class="form-control" id="user_country" name="user_country" onChange="return ajaxData();">
							<option value="">Country of Birth</option>
							// <? //if(count($countries)!='') {
							// foreach($countries as $country){ if($country->id_countries == $details->id_countries){?>
							<option value="<? //echo $country->id_countries;?>" selected="selected"><? //echo ucfirst($country->name);?></option>
							<? //} else{?>
							<option value="<? //echo $country->id_countries;?>"><? //echo ucfirst($country->name);?></option>
							<?//}}}?>
						</select>-->
						<input type="text" class="form-control" id="user_country" name="user_country" placeholder="Country of Birth">
					</div>
				</div>	
				<div class="form-group">
					<label for="inputpname" class="col-sm-3 control-label">Mobile Number</label>
					<div class="col-sm-8">
						<span class="error_msg_disp" id="user_mobile_req"></span>
						<input type="text" class="form-control" id="user_mobile" name="user_mobile" value="<? if(isset($details->mobile_number) && $details->mobile_number!='') {echo $details->mobile_number;}else{}?>" placeholder="Your Mobile Number">
					</div>
				</div>
				<div id="hideemployeeDiv">				
					<div class="form-group">
						<label for="inputpname" class="col-sm-3 control-label">Parent's First Name</label>
						<span class="error_msg_disp" id="user_parent_name_req"></span>
						<div class="col-sm-8">
							<input type="text" class="form-control" id="user_parent_name" name="user_parent_name"  value="<? if(isset($details->parents_name) && $details->parents_name!='') {echo ucfirst($details->parents_name);}else{}?>" placeholder="Parent's First Name">
						</div>
					</div>
					<div class="form-group">
						<label for="inputplname" class="col-sm-3 control-label">Parent's Last Name</label>
						<div class="col-sm-8">
							<span class="error_msg_disp" id="user_parent_lastname_req"></span>
							<input type="text" class="form-control" id="user_parent_lastname" name="user_parent_lastname" value="<? if(isset($details->user_parent_lastname) && $details->user_parent_lastname!='') {echo ucfirst($details->user_parent_lastname);}else{}?>" placeholder="Parent's Last Name">
						</div>
					</div>
					<div class="form-group">
						<label for="inputpnm" class="col-sm-3 control-label">Parent's Mobile</label>
						<div class="col-sm-8">
							<span class="error_msg_disp" id="user_parent_mobile_req"></span>
							<input type="text" class="form-control" id="user_mobile_number" name="user_mobile_number" value="<? if(isset($details->p_phone_number) && $details->p_phone_number!='') {echo $details->p_phone_number;}else{}?>"  placeholder="Parent's Mobile Number">
						</div>
					</div>
					<div class="form-group">
						<label for="inputpem" class="col-sm-3 control-label">Parent's Email</label>
						<div class="col-sm-8">
							<span class="error_msg_disp" id="user_parent_email_req"></span>
							<input type="text" class="form-control" id="user_parent_email" name="user_parent_email" value="<? if(isset($details->p_email_id) && $details->p_email_id!='') {echo $details->p_email_id;}else{}?>" placeholder="Parent's Email Address">
						</div>
					</div>
					<div class="form-group">
						<label for="inputppin" class="col-sm-3 control-label">Parent's Postal Code</label>						
						<div class="col-sm-8">
							<span class="error_msg_disp" id="user_parent_pincode_req"></span>
							<input type="text" class="form-control" id="user_parent_pincode" name="user_parent_pincode" value="<? if(isset($details->p_pincode) && $details->p_pincode!='') {echo $details->p_pincode;}else{}?>" placeholder="Parent's Postal Code">
						</div>
					</div>
					<div class="form-group">
						<label for="inputperpin" class="col-sm-3 control-label">Your Postal Code</label>
						<div class="col-sm-8">
							<span class="error_msg_disp" id="user_parent_perment_pincode_req"></span>
							<input type="text" class="form-control" id="user_perment_pincode" name="user_perment_pincode" value="<? if(isset($details->permant_pincode) && $details->permant_pincode!='') {echo $details->permant_pincode;}else{}?>" placeholder="Your Postal Code">
						</div>
					</div>
					<div class="form-group">
						<label for="inputafi" class="col-sm-3 control-label">Annual Family Income</label>
						<div class="col-sm-8">
							<span class="error_msg_disp" id="user_annual_afi_req"></span>
							<input type="text" class="form-control" id="user_afi" name="user_afi" placeholder="Annual Family Income in Local Currency" value="<? if(isset($details->annual_family_income) && $details->annual_family_income!='') {echo $details->annual_family_income;}else{}?>" >
						</div>
					</div>
					<div class="form-group">
						<label for="inputfn" class="col-sm-3 control-label">Family Net Worth</label>
						<div class="col-sm-8">
							<span class="error_msg_disp" id="user_fnw_req"></span>
							<input type="text" class="form-control" id="user_fnw" name="user_fnw" placeholder="Family Net Worth" value="<? if(isset($details->family_net_worth) && $details->family_net_worth!='') {echo $details->family_net_worth;}else{}?>">
						</div>
					</div>
				</div>
				<div id="employeeDiv" style="display:none">
					<div class="form-group">
						<label for="inputPassword3" class="col-sm-3 control-label">Country of Job</label>
						<div class="col-sm-8">
							<span class="error_msg_disp" id="user_country_job_req"></span>
							<!--<select class="form-control" id="user_country" name="user_country" onChange="return ajaxData();">
								<option value="">Country of Birth</option>
								// <? //if(count($countries)!='') {
								// foreach($countries as $country){ if($country->id_countries == $details->id_countries){?>
								<option value="<? //echo $country->id_countries;?>" selected="selected"><? //echo ucfirst($country->name);?></option>
								<? //} else{?>
								<option value="<? //echo $country->id_countries;?>"><? //echo ucfirst($country->name);?></option>
								<?//}}}?>
							</select>-->
							<input type="text" class="form-control" id="user_country_job" name="user_country_job">
						</div>
					</div>
					<div class="form-group">
						<label for="inputectc" class="col-sm-3 control-label">Annual Income</label>
						<div class="col-sm-8">
							<span class="error_msg_disp" id="user_emp_ctc_req"></span>
							<input type="text" class="form-control" id="user_emp_ctc" name="user_emp_ctc" placeholder="Annual Income" value="<? if(isset($details->employee_ctc) && $details->employee_ctc!='') {echo $details->employee_ctc;}else{}?>">
						</div>
					</div>
					<div class="form-group">
						<label for="inputectc" class="col-sm-3 control-label">Company Website Url</label>
						<div class="col-sm-8">
							<span class="error_msg_disp" id="user_emp_websiteurl_req"></span>
							<input type="text" class="form-control" id="user_emp_websiteurl" name="user_emp_websiteurl" placeholder="Company Website Url" value="<? if(isset($details->employee_websiteurl) && $details->employee_websiteurl!='') {echo $details->employee_websiteurl;}else{}?>">
						</div>
					</div>
				</div>
				<div class="form-group">
					<div class="col-sm-8 col-lg-offset-3">
						<!--<button type="reset" class="btn btn-default">Cancel</button>-->
						<button type="button" class="btn btn-primary" onClick="validateReg(2);">Continue</button>
					</div>
				</div>
			</div>
			</div>
			<input type="hidden" id="hid_tab_2" name="hid_tab_2" value="0">
	</div>
			<div class="panel panel-default">
				<div class="panel-heading" onclick="regTab1(3,0)">High School/College-Grade 12 
					<i  id="icon3"class="glyphicon glyphicon-triangle-bottom  pull-right"></i>
				</div>
				<div class="panel-body" id="tab_3_hide" style="display:none;">
					<div class="form-horizontal">
						<div class="form-group">
							<label for="inputPassword3" class="col-sm-3 control-label">State/Province</label>
							<div class="col-sm-8">
								<span class="error_msg_disp" id="user_state_req"></span>
								<select class="form-control" id="user_state" name="user_state" onChange="return getDistricts();">
									<option value="">State where 12th completed</option>
									<? if(count($states)!='') {
									foreach($states as $state){ if($state->state_id == $details->state_id){?>
									<option value="<? echo $state->state_id;?>" selected="selected"><? echo ucfirst($state->state_name);?></option>
									<? } else{?>
									<option value="<? echo $state->state_id;?>"><? echo ucfirst($state->state_name);?></option>
									<?}}}?>
								</select>
							</div>
						</div>
						<div class="form-group">
							<label for="inputPassword3" class="col-sm-3 control-label">Country/District</label>
							<div class="col-sm-8">
								<span class="error_msg_disp" id="user_district_req"></span>
								<select class="form-control" id="user_district" name="user_district" onChange="return getColleges();">
								<option value="">District where 12th completed</option>
								<? if(count($districts)!='') {
								foreach($districts as $district){ if($details->district_id== $district->district_id){?>
								<option value="<? echo $district->district_id;?>" selected="selected"><? echo ucfirst($district->district_name);?></option>
								<? } else{?>
								<option value="<? echo $district->district_id;?>"><? echo ucfirst($district->district_name);?></option>
								<? } ?>
								<?}	}?>
								</select>
							</div>
						</div>
						<div class="form-group">
							<label for="inputcname" class="col-sm-3 control-label">High School</label>
							<div class="col-sm-8">
								<span class="error_msg_disp" id="user_colleges_req"></span>
								<select class="form-control" id="user_colleges" name="user_colleges">
									<option value="">Grade 12 High School Name</option>
									<? if(count($colleges)!='') {
									foreach($colleges as $college){ if( $details->college_name==$college->college_id){?>
									<option value="<? echo $college->college_id;?>" selected="selected"><? echo ucfirst($college->college_name);?></option>
									<? } else{?>
									<option value="<? echo $college->college_id;?>"><? echo ucfirst($college->college_name);?></option>
									<?}}}?>
								</select>
							</div>
						</div>
						<div class="form-group">
							<label for="inputpname" class="col-sm-3 control-label">Principal's Name</label>
							<div class="col-sm-8">
								<span class="error_msg_disp" id="user_principal_name_req"></span>
								<input type="text" class="form-control" id="user_principal_name" name="user_principal_name" placeholder="Principal's Name" value="<? if(isset($details->principal_name) && $details->principal_name!='') {echo ucfirst($details->principal_name);}else{}?>" >
							</div>
						</div>
						<div class="form-group">
							<label for="inputpnmb" class="col-sm-3 control-label">Principal's Mobile</label>
							<div class="col-sm-8">
								<span class="error_msg_disp" id="user_princi_phone_req"></span>
								<input type="text" class="form-control" id="user_princi_phone" name="user_princi_phone" placeholder="Principal's Mobile Number" value="<? if(isset($details->principal_phone_num) && $details->principal_phone_num!='') {echo $details->principal_phone_num;}else{}?>" >
							</div>
						</div>
						<div class="form-group">
							<label for="inputpemail" class="col-sm-3 control-label">Principal's Email</label>
							<div class="col-sm-8">
								<span class="error_msg_disp" id="user_princi_email_req"></span>
								<input type="text" class="form-control" id="user_princi_email" name="user_princi_email" value="<? if(isset($details->principal_email_id) && $details->principal_email_id!='') {echo $details->principal_email_id;}else{}?>" placeholder="Principal's Email Address">
							</div>
						</div>
						<div class="form-group">
							<div class="col-sm-8 col-lg-offset-3">
								<!--<button type="reset" class="btn btn-default">Cancel</button>-->
								<button type="button" class="btn btn-primary" onClick="validateReg(3);">Continue</button>
							</div>
						</div>
					</div>
				</div>
				<input type="hidden" id="hid_tab_3" name="hid_tab_3" value="0">
			</div>
			<div class="panel panel-default">
				<div class="panel-heading" onclick="regTab1(4,0)">College Readiness Entrance Exam Score/Rank
					<i  id="icon4"class="glyphicon glyphicon-triangle-bottom  pull-right"></i>
				</div>
				<div class="panel-body" id="tab_4_hide" style="display:none;">
					<div class="form-horizontal">
			<!-- Entrance Exam 1-------->
						<div class="form-group">
							<div class="col-sm-3">
								<span class="error_msg_disp1" id="user_entrance_year_req"></span>
								<label class="control-label" for="focusedInput">Year of Exam</label>
								<select class="form-control" id="user_entrance_year" name="user_entrance_year">
								<option value="">Year of Test</option>
								<? $i=1;for($i=1960;$i<=2015;$i++){ if( $details->which_year == $i){?>
								<option value="<? echo $i;?>" selected="selected"><? echo $i;?></option>
								<? } else{?>
								<option value="<? echo $i;?>"><? echo $i;?></option>
								<? } ?>
								<?}?>
								</select>
							</div>
							<div class="col-sm-3">
								<label class="control-label" for="focusedInput">Test/Exam</label>
								<span class="error_msg_disp1" id="user_entrance_exam_req"></span>
								<select class="form-control" id="user_entrance_exam" name="user_entrance_exam">
								<option value="">Exam Name</option>
								<? if(count($entranceexams)!='') {
								foreach($entranceexams as $entranceExam){ if( $details->entrance_exam == $entranceExam->entrance_exam_id){?>
									<option value="<? echo $entranceExam->entrance_exam_id;?>" selected="selected"><? echo ucfirst($entranceExam->entrance_exam_name);?></option>
								<? } else{?>
									<option value="<? echo $entranceExam->entrance_exam_id;?>"><? echo ucfirst($entranceExam->entrance_exam_name);?></option>
								<?}	}}?>
								</select>
							</div>
							<div class="col-sm-3">
								<label class="control-label" for="focusedInput">Score/Rank</label>
								<span class="error_msg_disp1" id="user_entrance_rank_req"></span>
								<input class="form-control" id="user_entrance_rank" name="user_entrance_rank" type="text" value="<? if(isset($details->entrance_rank) && $details->entrance_rank!='') {echo $details->entrance_rank;}else{}?>" placeholder="Exam Rank">
							</div>							
						</div>
		<!-- Entrance Exam 2-------->
						<div class="form-group">
							<div class="col-sm-3">
								<label class="control-label" for="focusedInput">Year of Exam</label>
								<select class="form-control" id="user_entrance_year_1" name="user_entrance_year_1">
								<option value="">Year of Test</option>
								<? $i=1;for($i=1960;$i<=2015;$i++){ if( $details->which_year_1 == $i){?>
								<option value="<? echo $i;?>" selected="selected"><? echo $i;?></option>
								<? } else{?>
								<option value="<? echo $i;?>"><? echo $i;?></option>
								<? } ?>
								<?}?>
								</select>
							</div>
							<div class="col-sm-3">
								<label class="control-label" for="focusedInput">Test/Exam</label>
								<select class="form-control" id="user_entrance_exam_1" name="user_entrance_exam_1">
								<option value="">Exam Name</option>
								<? if(count($entranceexams)!='') {
								foreach($entranceexams as $entranceExam){ if( $details->entrance_exam_1 == $entranceExam->entrance_exam_id){?>
									<option value="<? echo $entranceExam->entrance_exam_id;?>" selected="selected"><? echo ucfirst($entranceExam->entrance_exam_name);?></option>
								<? } else{?>
									<option value="<? echo $entranceExam->entrance_exam_id;?>"><? echo ucfirst($entranceExam->entrance_exam_name);?></option>
								<?}	}}?>
								</select>
							</div>
							<div class="col-sm-3">
								<label class="control-label" for="focusedInput">Score/Rank</label>
								<span class="error_msg_disp1" id="user_entrance_op_1"></span>
								<input class="form-control" id="user_entrance_rank_1" name="user_entrance_rank_1" type="text" value="<? if(isset($details->entrance_rank_1) && $details->entrance_rank_1!='') {echo $details->entrance_rank_1;}else{}?>" placeholder="Exam Rank">
							</div>							
						</div>
			<!-- Entrance Exam 3-------->
						<div class="form-group">
							<div class="col-sm-3">
								<label class="control-label" for="focusedInput">Year of Exam</label>
								<select class="form-control" id="user_entrance_year_2" name="user_entrance_year_2">
								<option value="">Year of Test</option>
								<? $i=1;for($i=1960;$i<=2015;$i++){ if( $details->which_year_2 == $i){?>
								<option value="<? echo $i;?>" selected="selected"><? echo $i;?></option>
								<? } else{?>
								<option value="<? echo $i;?>"><? echo $i;?></option>
								<? } ?>
								<?}?>
								</select>
							</div>
							<div class="col-sm-3">
								<label class="control-label" for="focusedInput">Test/Exam</label>
								<select class="form-control" id="user_entrance_exam_2" name="user_entrance_exam_2">
								<option value="">Exam Name</option>
								<? if(count($entranceexams)!='') {
								foreach($entranceexams as $entranceExam){ if( $details->entrance_exam_2 == $entranceExam->entrance_exam_id){?>
									<option value="<? echo $entranceExam->entrance_exam_id;?>" selected="selected"><? echo ucfirst($entranceExam->entrance_exam_name);?></option>
								<? } else{?>
									<option value="<? echo $entranceExam->entrance_exam_id;?>"><? echo ucfirst($entranceExam->entrance_exam_name);?></option>
								<?}	}}?>
								</select>
							</div>
							<div class="col-sm-3">
								<label class="control-label" for="focusedInput">Score/Rank</label>
								<span class="error_msg_disp1" id="user_entrance_op_2"></span>
								<input class="form-control" id="user_entrance_rank_2" name="user_entrance_rank_2" type="text" value="<? if(isset($details->entrance_rank_2) && $details->entrance_rank_2!='') {echo $details->entrance_rank_2;}else{}?>" placeholder="Exam Rank">
							</div>
							<div class="col-sm-3">
								<label class="control-label" for="focusedInput">&nbsp;</label><br/>
								<button type="button" class="btn btn-primary" onClick="validateReg(4);">Continue</button>
							</div>
						</div>
				<!--- End ------->
					</div>
				</div>
				<input type="hidden" id="hid_tab_4" name="hid_tab_4" value="0">
			</div>
			<div class="panel panel-default">
				<div class="panel-heading" onclick="regTab1(5,0)">Bachelor's Degree Details
				<i  id="icon5"class="glyphicon glyphicon-triangle-bottom  pull-right"></i></div>
				<div class="panel-body" id="tab_5_hide" style="display:none;">
				<div class="form-horizontal">
					<div class="form-group">
						<label for="select" class="col-sm-3 control-label">Degree Name</label>
						<div class="col-sm-8">
							<span class="error_msg_disp" id="user_bac_degree_req"></span>
							<!--<select class="form-control" id="user_bac_degree" name="user_bac_degree">
								<option value="">Select Bachelor's Degree</option>
								<?// if(count($b_degrees)!='') {
								//foreach($b_degrees as $bachDegree){ if($bachDegree->degree_id == $details->bachelors_degree_name ){?>
								<option value="<? //echo $bachDegree->degree_id;?>" selected="selected"><? //echo ucfirst($bachDegree->degree_name);?></option>
								<?//} else{?>
								<option value="<? //echo $bachDegree->degree_id;?>"><? //echo ucfirst($bachDegree->degree_name);?></option>
								<?//}	}}?>
							</select>-->
							<input type="text" id="user_bac_degree" name="user_bac_degree" value="Bachelor's"  class="form-control" readonly="readonly">
						</div>
					</div>
					<div class="form-group">
						<label for="select" class="col-sm-3 control-label">Major/Specialization</label>
						<div class="col-sm-8">
							<span class="error_msg_disp" id="user_bac_speclization_req"></span>
							<select class="form-control" id="user_bac_speclization" name="user_bac_speclization">
								<option value="">Select Specialization </option>
								<? if(count($specializations)!='') {
								foreach($specializations as $specialization){ if($specialization->specialined_id == $details->bachelors_specialization){?>
								<option value="<? echo $specialization->specialined_id;?>" selected="selected"><? echo ucfirst($specialization->specialined_name);?></option>
								<? } else{?>
								<option value="<? echo $specialization->specialined_id;?>"><? echo ucfirst($specialization->specialined_name);?></option>
								<? } ?>
								<?}	}?>
							</select>
						</div>
					</div>
					<div class="form-group">
						<label for="select" class="col-sm-3 control-label">Country</label>
						<div class="col-sm-8">
							<input type="text" class="form-control" id="user_bachelors_country" name="user_bachelors_country" Placeholder="Country of bachelor's study">
						</div>
					</div>
					<div class="form-group">
						<label for="select" class="col-sm-3 control-label">University</label>
						<div class="col-sm-8">
							<span class="error_msg_disp" id="user_bac_unversity_req"></span>
							<select class="form-control" id="user_bac_unversity" name="user_bac_unversity">
							<option value="">Select University</option>
							<? if(count($unversities)!='') {
							foreach($unversities as $unversity){ if( $unversity->unversity_id == $details->bachelors_university_name){?>
							<option value="<? echo $unversity->unversity_id;?>" selected="seletced"><? echo ucfirst($unversity->unversity_name);?></option>
							<?} else{?>
							<option value="<? echo $unversity->unversity_id;?>"><? echo ucfirst($unversity->unversity_name);?></option>
							<?}	}}?>
							</select>
						</div>
					</div>
					<div class="form-group">
						<label for="select" class="col-sm-3 control-label">Univ College</label>
						<div class="col-sm-8">
							<span class="error_msg_disp" id="user_bac_college_req"></span>
							<select class="form-control" id="user_bac_college" name="user_bac_college">
							<option value="">Select College </option>
							<? if(count($colleges)!='') {
							foreach($colleges as $college){ if($college->college_id == $details->bachelors_college){?>
							<option value="<? echo $college->college_id;?>" selected="selected"><? echo ucfirst($college->college_name);?></option>
							<? } else{?>
							<option value="<? echo $college->college_id;?>"><? echo ucfirst($college->college_name);?></option>
							<?}}}?>
							</select>
						</div>
					</div>
					
					<div class="form-group">
						<label for="select" class="col-sm-3 control-label">Year of Admission</label>
						<div class="col-sm-8">
							<span class="error_msg_disp" id="user_bac_year_req"></span>
							<select class="form-control" id="user_bac_year" name="user_bac_year">
							<option value="">Select Year</option>
							<? $i=1;for($i=1960;$i<=2015;$i++){ if( $i == $details->bachelors_year_admission){?>
							<option value="<? echo $i;?>" selected="selected"><? echo $i;?></option>
							<? } else{?>
							<option value="<? echo $i;?>"><? echo $i;?></option>
							<? } ?>
							<?}?>
							</select>
						</div>
					</div>
					<div class="form-group">
					<div class="col-sm-8 col-lg-offset-3">
					<!--<button type="reset" class="btn btn-default">Cancel</button>-->
					<button type="button" class="btn btn-primary" onClick="validateReg(5);">Continue</button>
					</div>
					</div>
				</div>
				<input type="hidden" id="hid_tab_5" name="hid_tab_5" value="0">
				</div>
			</div>
	<div class="panel panel-default">
			<div class="panel-heading" onclick="regTab1(6,0)">Master's Degree Details
			<i  id="icon5"class="glyphicon glyphicon-triangle-bottom  pull-right"></i></div>
			<div class="panel-body" id="tab_6_hide" style="display:none;">
			<div class="form-horizontal">
			<div class="form-group">
			<label for="select" class="col-sm-3 control-label">Degree Name</label>
			<div class="col-sm-8">
			<span class="error_msg_disp" id="user_master_degree_req"></span>
			<!--<select class="form-control" id="user_master_degree" name="user_master_degree">
			<option value="">Select Masters Degree</option>
			<?// if(count($m_degrees)!='') {
			//foreach($m_degrees as $masdegrees){ if($masdegrees->masters_degree_id == $details->masters_degree){?>
			<option value="<? //echo $masdegrees->masters_degree_id;?>" selected="selected"><? //echo ucfirst($masdegrees->mas_degree_name);?></option>
			<?// } else{?>
			<option value="<? //echo $masdegrees->masters_degree_id;?>"><? //echo ucfirst($masdegrees->mas_degree_name);?></option>
			<?// } ?>
			<?//}	}?>
			</select>-->
			<input type="text" id="user_master_degree" name="user_master_degree" value="Master's"  class="form-control" readonly="readonly">
			</div>
			</div>
			<div class="form-group">
			<label for="select" class="col-sm-3 control-label">Major/Specialization</label>
			<div class="col-sm-8">
			<span class="error_msg_disp" id="user_mast_spec_req"></span>
			<select class="form-control" id="user_mast_spec" name="user_mast_spec">
			<option value="">Select Specialization </option>
			<? if(count($specializations)!='') {
			foreach($specializations as $specialization){ if($specialization->specialined_id == $details->masters_specialization){?>
			<option value="<? echo $specialization->specialined_id;?>" selected="selected"><? echo ucfirst($specialization->specialined_name);?></option>
			<? }else{?>
			<option value="<? echo $specialization->specialined_id;?>"><? echo ucfirst($specialization->specialined_name);?></option>
			<?} ?>
			<?}	}?>
			</select>
			</div>
			</div>
			<div class="form-group">
			<label for="select" class="col-sm-3 control-label">Country</label>
			<div class="col-sm-8">
				<input type="text" class="form-control" id="user_masters_country" name="user_masters_country" Placeholder="Country of master's study">
			</div>
			</div>
			<div class="form-group">
			<label for="select" class="col-sm-3 control-label">University</label>
			<div class="col-sm-8">
			<span class="error_msg_disp" id="user_mast_university_req"></span>
			<select class="form-control" id="user_mast_university" name="user_mast_university">
			<option value="">Select University</option>
			<? if(count($unversities)!='') {
			foreach($unversities as $unversity){ if( $unversity->unversity_id == $details->masters_university){ ?>
				<option value="<? echo $unversity->unversity_id;?>" selected="selected"><? echo ucfirst($unversity->unversity_name);?></option>
			<? } else{?>
				<option value="<? echo $unversity->unversity_id;?>"><? echo ucfirst($unversity->unversity_name);?></option>
			<?}	}}?>
			</select>
			</div>
			</div>
			<div class="form-group">
			<label for="select" class="col-sm-3 control-label">College</label>
			<div class="col-sm-8">
			<span class="error_msg_disp" id="user_mast_college_req"></span>
			<select class="form-control" id="user_mast_college" name="user_mast_college">
			<option value="">Select College </option>
			<? if(count($colleges)!='') {
			foreach($colleges as $college){ if($college->college_id == $details->masters_college){?>
			<option value="<? echo $college->college_id;?>" selected="selected"><? echo ucfirst($college->college_name);?></option>
			<? }else{?>
			<option value="<? echo $college->college_id;?>"><? echo ucfirst($college->college_name);?></option>
			<?} ?>
			<?}	}?>
			</select>
			</div>
			</div>
		
			<div class="form-group">
			<label for="select" class="col-sm-3 control-label">Year of Admission</label>
			<div class="col-sm-8">
			<span class="error_msg_disp" id="user_mast_year_req"></span>
			<select class="form-control" id="user_mast_year" name="user_mast_year">
			<option value="">Select Year</option>
			<? $i=1;for($i=1960;$i<=2015;$i++){ if( $i == $details->masters_year_admission){?>
			<option value="<? echo $i;?>" selected="selected"><? echo $i;?></option>
			<? } else{?>
			<option value="<? echo $i;?>"><? echo $i;?></option>
			<? } ?>
			<?}?>
			</select>
			</div>
			</div>
			<div class="form-group">
			<div class="col-sm-8 col-lg-offset-3">
			<!--<button type="reset" class="btn btn-default">Cancel</button>-->
			<button type="button" class="btn btn-primary" onClick="validateReg(6);">Continue</button>
			</div>
			</div>
			</div>
			<input type="hidden" id="hid_tab_6" name="hid_tab_6" value="0">
			</div>
		</div>
		<div class="panel panel-default">
			<div class="panel-heading" onclick="regTab1(7,0)">Doctoral Degree Details
			<i  id="icon5"class="glyphicon glyphicon-triangle-bottom  pull-right"></i></div>
			<div class="panel-body" id="tab_7_hide" style="display:none;">
			<div class="form-horizontal">
			<div class="form-group">
			<label for="inputcname" class="col-sm-3 control-label">PhD</label>
			<div class="col-sm-8">
			<span class="error_msg_disp" id="user_doctor_phd_req"></span>
			<input type="text" class="form-control" id="user_doctor_phd" name="user_doctor_phd" value="PhD" readonly="readonly" placeholder="PhD">
			</div>
			</div>
			<div class="form-group">
			<label for="select" class="col-sm-3 control-label">Major/Specialization</label>
			<div class="col-sm-8">
			<span class="error_msg_disp" id="user_doctor_spec_req"></span>
			<select class="form-control" id="user_doctor_spec" name="user_doctor_spec">
			<option value="">Select Specialization</option>
			<? if(count($specializations)!='') {
			foreach($specializations as $specialization){ if($specialization->specialined_id == $details->doctorate_specialization){?>
			<option value="<? echo $specialization->specialined_id;?>" selected="selected"><? echo ucfirst($specialization->specialined_name);?></option>
			<?} else{?>
			<option value="<? echo $specialization->specialined_id;?>"><? echo ucfirst($specialization->specialined_name);?></option>
			<? }?>
			<?}	}?>
			</select>
			</div>
			</div>
			<div class="form-group">
			<label for="select" class="col-sm-3 control-label">Country</label>
			<div class="col-sm-8">
				<input type="text" class="form-control" id="user_doctoral_country" name="user_doctoral_country" Placeholder="Country of doctoral study">
			</div>
			</div>
			<div class="form-group">
			<label for="select" class="col-sm-3 control-label">University</label>
			<div class="col-sm-8">
			<span class="error_msg_disp" id="user_doctor_university_req"></span>
			<select class="form-control" id="user_doctor_university" name="user_doctor_university">
			<option value="">Select University</option>
			<? if(count($unversities)!='') {
			foreach($unversities as $unversity){  if( $unversity->unversity_id == $details->doctorate_university){?>
			<option value="<? echo $unversity->unversity_id;?>" selected="seletced"><? echo ucfirst($unversity->unversity_name);?></option>
			<? } else{?>
			<option value="<? echo $unversity->unversity_id;?>"><? echo ucfirst($unversity->unversity_name);?></option>
			<?} ?>
			<?}	}?>
			</select>
			</div>
			</div>
			<div class="form-group">
			<label for="select" class="col-sm-3 control-label">College</label>
			<div class="col-sm-8">
			<span class="error_msg_disp" id="user_doctor_college_req"></span>
			<select class="form-control" id="user_doctor_college" name="user_doctor_college">
			<option value="">Select College </option>
			<? if(count($colleges)!='') {
			foreach($colleges as $college){ if($college->college_id == $details->doctorate_college){?>
			<option value="<? echo $college->college_id;?>" selected="selected"><? echo ucfirst($college->college_name);?></option>
			<? } else{?>
			<option value="<? echo $college->college_id;?>"><? echo ucfirst($college->college_name);?></option>
			<?  }?>
			<?}	}?>
			</select>
			</div>
			</div>
			
			<div class="form-group">
			<label for="select" class="col-sm-3 control-label">Year of Admission</label>
			<div class="col-sm-8">
			<span class="error_msg_disp" id="user_doctor_year_req"></span>
			<select class="form-control" id="user_doctor_year" name="user_doctor_year">
			<option value="">Select Year</option>
			<? $i=1;for($i=1960;$i<=2015;$i++){ if( $i == $details->doctorate_year){?>
			<option value="<? echo $i;?>" selected="selected"><? echo $i;?></option>
			<? } else{?>
			<option value="<? echo $i;?>"><? echo $i;?></option>
			<? } ?>
			<?}?>
			</select>
			</div>
			</div>
			<div class="form-group">
			<div class="col-sm-8 col-lg-offset-3">
			<!--<button type="reset" class="btn btn-default">Cancel</button>-->
			<button type="button" class="btn btn-primary" onClick="validateReg(7);">Continue</button>
			</div>
			</div>
			</div>
			</div>
		</div>
			<div class="form-group text-center">
				<div class="">
					<button type="button" class="btn btn-primary" style="width:30%;" onCLick="formFinalSubmit();">Save</button>
				</div>
			</div>
			<input type="hidden" id="hid_user_id" name="hid_user_id" value="<? if(isset($details->user_id) && $details->user_id!=''){ echo $details->user_id;}else{}?>">
		<input type="hidden" id="opentabId" value="1">
		</form>			
		</div>
		</div>	
	</div>
</div>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <? $list_countries=''; if(count($this->countries)!='') {
		foreach($this->countries as $key=>$search){
			$list_countries[$key]=$search->name;
		}		
	}
?>
<script> 
$(function() {	
	$("#user_country").autocomplete({	
		source: function( request, response ) {
			var keywordsss = $('#user_country').val();
			var hashName='s';
			$.ajax({
				url: BASE_URL+'/users/search-country-names',
				dataType: "json",
				type	: "POST",
				data	:{value:keywordsss},
				success: function( data ) {
					if(data.output!=0) {		
						response( $.map( data.searchHashNames, function( item ) {
							return {
								label: item.ref,
							}
						}));
					}else{
						$(".ui-autocomplete").css("display","none");
					}
				}				
			});
		},
		minLength: 0,	
		open: function(event, ui) {				
			// $(".ui-autocomplete").css("width","876px !important");
		},
		select: function(event, ui) {
			$("#user_country").val(ui.item.label); 
			return false;
		},
		focus: function(event, ui) {
			return false;
		}			
	});
	$("#user_country").data( "autocomplete" )._renderItem = function( ul, item ) {
		var hashname=item.label;		
		 return $("<li><a data-value='"+item.label+"' onClick ='set_item(this.text);'>" + item.label + "</a></li>")
		 .data("item.autocomplete", item)            
		 .appendTo(ul);				
	};
});
$( document ).ready(function() {
    switchinUser();
});
</script>