 <div class="container min_height">
  <div id="loginModal" class="show"  role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="alert alert-dismissible alert-success" style="display:none" id="sucessdiv">
		<strong id="sucessMsg"></strong>
 </div>
 <div class="alert alert-dismissible alert-danger" style="display:none" id="errordiv">
		<strong id="errorMsg"></strong>
	</div>
  <?php if(isset($this->existtoken)&& ($this->existtoken==1)){?>	
  <div class="modal-content">
      <div class="modal-header">
          <h1 class="text-center">Reset Password to Poraapo</h1>
      </div>
      <div class="modal-body">
		<span id="sucessMsg" style="color:green"></span>
		<span id="errorMsg" style="color:red"></span>
          <form id="resetPasswordForm" class="form col-md-12 center-block" method="POST">
			<div class="form-group">
              <input type="password" class="form-control " id="newPassword" name="newPassword" placeholder="New Password">
            </div>
			 <span id="newPwdError" style="color:red"></span>
			<div class="form-group">
              <input type="password" class="form-control "  id="confirmPassword" name="confirmPassword" placeholder="Confirm Password">
            </div>
			 <span id="confirmPwdError" style="color:red"></span>
            <div class="form-group">
              <button id="button" type="button" class="btn btn-primary btn-block" onclick="resetPassword(1)">Save</button>
			  <center><span id="reload"></span></center>
            </div>
			<input type="hidden" id="hidToken" name="hidToken" value="<?php echo $_GET['token']; ?>"/>
          </form>
      </div><div class="clearfix"></div>
  </div>
 <script>
		$('#confirmPassword').keypress(function(e){
			if( e.keyCode == 13 ){
				resetPassword(1);	
			}
		});
</script>
  <?}else{?>
				<div class="modal-content">
      <div class="modal-header">
          <h1 class="text-center">Expired Message</h1>
      </div>
      <div class="modal-body">
	  <p>Your gotten URL is expired. Please try once again...</p>
      </div><div class="clearfix"></div>
  </div>
<?}?>	
  </div>
</div>
</div>
