<?php if(isset($_SESSION['user']['user_type_id']) && $_SESSION['user']['user_type_id']=='4'){?>
<?php } else {?>
	<div class="container min_height"><br/>
		<div class="mar_t">
			<div class="row">
				<div class="col-md-12 columan_divs">
					<div class="panel panel-default">
						<div class="panel-heading"><h3>Welcome to Start class</h3></div>
						<div class="panel-body">
							<div>
								<div class="testimonial">
									<p class="testimonial_f">Updated The education system encourages a lot of rote learning. The education system encourages a lot of rote learning.
									The education system encourages a lot of rote learning.The education system encourages a lot of rote learning.
									The education system encourages a lot of rote learning.The education system encourages a lot of rote learning.</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div> 
<?php } ?>
