	<div class="container reg_w_12 min_height"> <br/>
	<?php if(isset($_GET['suc']) && $_GET['suc']=='udt'){?>
			<div class="alert alert-dismissible alert-success">
				<button type="button" class="close" data-dismiss="alert">×</button>
				<strong>Updated Successfully.</strong>
			</div>
		<?}else if(isset($_GET['suc']) && $_GET['suc']=='reg'){?>
			<div class="alert alert-dismissible alert-success">
				<button type="button" class="close" data-dismiss="alert">×</button>
				<strong>Registration Successfully.</strong>
			</div>
		<? } ?>
	<div class="panel panel panel-default mar_t">		
		<? $base_user_id =''; if(isset($_SESSION['user'])){
				$base_user_id = base64_encode($_SESSION['user']['user_id']);
			}?>
		<div class="panel-heading reg_bg">
			<h3 class="panel-title">View Profile</h3>
			<div class="view_profile_r"><a href="<?php echo $baseUrl; ?>/users/register?uid=<? echo $base_user_id;?>">Edit Profile</a></div>
		</div> 
		<? $details=''; if(count($this->userDetails)!=0){ foreach($this->userDetails as $detailss){ $details = $detailss;}}?>
		<div class="panel-body">
			<div class="panel panel-default">
				<div class="panel-heading" id="tab_1" onclick="regTab1(1)">Login Deatils
				<i id="icon1" class="glyphicon glyphicon-triangle-top  pull-right"></i></div>
				<div class="panel-body" id="tab_1_hide">
				<form class="form-horizontal">
				<div class="form-group">
				<label for="inputtype" class="col-sm-3 control-label">User Type :</label>
				<div class="col-sm-8">
					<p class="form-control-static">
						<? if(count($usertypes)!='') {
						foreach($usertypes as $user_type){ if($details->user_type_id == $user_type->user_type_id){?>
						<? echo ucfirst($user_type->user_type_name);?>
						<?}	} } ?>
					</p>
				</div>
				</div>
				<div class="form-group">
				<label for="inputEmail3" class="col-sm-3 control-label">Email :</label>
				<div class="col-sm-8">
				<p class="form-control-static"><? if(isset($details->email_id) && $details->email_id!='') {echo $details->email_id;}else{}?></p>
				</div>
				</div>
				
				</div>
				</form>
				</div>
		
			<div class="panel panel-default">
				<div class="panel-heading" onclick="regTab1(2)">Personal Information 
				<i  id="icon2"class="glyphicon glyphicon-triangle-bottom  pull-right"></i></div>
				<div class="panel-body" id="tab_2_hide" style="display:none;">
				<form class="form-horizontal">
				<div class="form-group">
				<label for="inputfname" class="col-sm-3 control-label">First Name</label>
				<div class="col-sm-8">
					<p class="form-control-static"><? if(isset($details->first_name) && $details->first_name!='') {echo ucfirst($details->first_name);}else{}?></p>
				</div>
				</div>
				<div class="form-group">
				<label for="inputlname" class="col-sm-3 control-label">Last Name</label>
				<div class="col-sm-8">
					<p class="form-control-static"><? if(isset($details->last_name) && $details->last_name!='') {echo ucfirst($details->last_name);}else{}?></p>
				</div>
				</div>
				<div class="form-group">
				<label class="col-sm-3 control-label">Gender</label>
				<div class="col-sm-8">
					<p class="form-control-static"><? if(isset($details->gender) && $details->gender!='') {echo ucfirst($details->gender);}else{}?></p>
				</div>
				</div>
				<div class="form-group">
				<label for="inputEmail3" class="col-sm-3 control-label">Date of Birth</label>
				<div class="col-sm-3">
					<p class="form-control-static"><? if(isset($details->date_of_birth) && $details->date_of_birth!='') {echo ucfirst($details->date_of_birth);}else{}?></p>
				</div>
				</div>
				<div class="form-group">
				<label for="inputPassword3" class="col-sm-3 control-label">Country</label>
				<div class="col-sm-8">
				<p class="form-control-static"><? if(count($countries)!='') {
							foreach($countries as $country){ if($country->id_countries == $details->id_countries){?>
							<? echo ucfirst($country->name);?>
							<?}	}}?></p>
				</div>
				</div>	
				<div class="form-group">
				<label for="inputpname" class="col-sm-3 control-label">Mobile Number</label>
				<div class="col-sm-8">
					<p class="form-control-static"><? if(isset($details->mobile_number) && $details->mobile_number!='') {echo $details->mobile_number;}else{}?></p>
				</div>
				</div>	
			<?if(isset($details->user_type_id) && $details->user_type_id==1){?>
				<div id="hideemployeeDiv">				
				<div class="form-group">
				<label for="inputpname" class="col-sm-3 control-label">Parent's First Name</label>
				<div class="col-sm-8">
					<p class="form-control-static"><? if(isset($details->parents_name) && $details->parents_name!='') {echo ucfirst($details->parents_name);}else{}?></p>
				</div>
				</div>
				<div class="form-group">
				<label for="inputplname" class="col-sm-3 control-label">Parent's Last Name</label>
				<div class="col-sm-8">
					<p class="form-control-static"><? if(isset($details->user_parent_lastname) && $details->user_parent_lastname!='') {echo ucfirst($details->user_parent_lastname);}else{}?></p>
				</div>
				</div>
				<div class="form-group">
				<label for="inputpnm" class="col-sm-3 control-label">Parent's Mobile Number</label>
				<div class="col-sm-8">
					<p class="form-control-static"><? if(isset($details->p_phone_number) && $details->p_phone_number!='') {echo $details->p_phone_number;}else{}?></p>
				</div>
				</div>
				<div class="form-group">
				<label for="inputpem" class="col-sm-3 control-label">Parent's Email</label>
				<div class="col-sm-8">
					<p class="form-control-static"><? if(isset($details->p_email_id) && $details->p_email_id!='') {echo $details->p_email_id;}else{}?></p>
				</div>
				</div>
				<div class="form-group">
				<label for="inputppin" class="col-sm-3 control-label">Parent's Pincode</label>
				<div class="col-sm-8">
					<p class="form-control-static"><? if(isset($details->p_pincode) && $details->p_pincode!='') {echo $details->p_pincode;}else{}?></p>
				</div>
				</div>
				<div class="form-group">
				<label for="inputppin" class="col-sm-3 control-label">Permant Pincode</label>
				<div class="col-sm-8">
					<p class="form-control-static"><? if(isset($details->permant_pincode) && $details->permant_pincode!='') {echo $details->permant_pincode;}else{}?></p>
				</div>
				</div>
				<div class="form-group">
				<label for="inputafi" class="col-sm-3 control-label">Annual Family Income</label>
				<div class="col-sm-8">
					<p class="form-control-static"><? if(isset($details->annual_family_income) && $details->annual_family_income!='') {echo $details->annual_family_income;}else{}?></p>
				</div>
				</div>
				<div class="form-group">
				<label for="inputfn" class="col-sm-3 control-label"> Family Net Worth</label>
				<div class="col-sm-8">
					<p class="form-control-static"><? if(isset($details->family_net_worth) && $details->family_net_worth!='') {echo $details->family_net_worth;}else{}?></p>
				</div>
				</div>
				</div>
				<? } ?>
				<?if(isset($details->user_type_id) && $details->user_type_id==2){?>
					<div id="employeeDiv">
					<div class="form-group">
					<label for="inputectc" class="col-sm-3 control-label">Employee CTC</label>
					<div class="col-sm-8">
						<p class="form-control-static"><? if(isset($details->employee_ctc) && $details->employee_ctc!='') {echo $details->employee_ctc;}else{}?></p>
					</div>
					</div>
					</div>
				<? } ?>
				</form>
				</div>
			</div>
			<div class="panel panel-default">
				<div class="panel-heading" onclick="regTab1(3)">12th Class College Information 
				<i  id="icon3"class="glyphicon glyphicon-triangle-bottom  pull-right"></i></div>
				<div class="panel-body" id="tab_3_hide" style="display:none;">
				<form class="form-horizontal">
				<div class="form-group">
				<label for="inputPassword3" class="col-sm-3 control-label">State Name</label>
				<div class="col-sm-8">
				<p class="form-control-static"> <? if(count($states)!='') {
					foreach($states as $state){ if($state->state_id == $details->state_id){?>
					<? echo ucfirst($state->state_name);?>
				<?}	} } ?></p>
				</div>
				</div>
				<div class="form-group">
				<label for="inputPassword3" class="col-sm-3 control-label">District Name</label>
				<div class="col-sm-8">
				<p class="form-control-static">
					<? if(count($districts)!='') {
					foreach($districts as $district){ if($district->district_id == $details->district_id){?>
					<? echo ucfirst($district->district_name);?>
					<?}	} }?>
				</p>
				</div>
				</div>
				<div class="form-group">
				<label for="inputcname" class="col-sm-3 control-label">College Name</label>
				<div class="col-sm-8">
					<p class="form-control-static">
						<? if(count($colleges)!='') {
							foreach($colleges as $college){ if($college->college_id == $details->college_name){?>
							<? echo ucfirst($college->college_name);?>
						<?}	}}?>
					</p>
				</div>
				</div>
				<div class="form-group">
				<label for="inputpname" class="col-sm-3 control-label">Principal's Name</label>
				<div class="col-sm-8">
					<p class="form-control-static"><? if(isset($details->principal_name) && $details->principal_name!='') {echo ucfirst($details->principal_name);}else{}?></p>
				</div>
				</div>
				<div class="form-group">
				<label for="inputpnmb" class="col-sm-3 control-label">Principal's Mobile Number</label>
				<div class="col-sm-8">
					<p class="form-control-static"><? if(isset($details->principal_phone_num) && $details->principal_phone_num!='') {echo $details->principal_phone_num;}else{}?></p>
				</div>
				</div>
				<div class="form-group">
				<label for="inputpemail" class="col-sm-3 control-label">Principal's Email</label>
				<div class="col-sm-8">
					<p class="form-control-static"><? if(isset($details->principal_email_id) && $details->principal_email_id!='') {echo $details->principal_email_id;}else{}?></p>
				</div>
				</div>
				</form>
				</div>
			</div>
			<div class="panel panel-default">
				<div class="panel-heading" onclick="regTab1(4)">Entrance Exam Information
				<i  id="icon4"class="glyphicon glyphicon-triangle-bottom  pull-right"></i></div>
				<div class="panel-body" id="tab_4_hide" style="display:none;">
					<div class="form-horizontal">
						<div class="form-group">
							<div class="col-sm-3">
								<label class="control-label" for="focusedInput">Year</label>
								<p class="form-control-static">
									<? if(isset($details->which_year) && $details->which_year!='') {echo $details->which_year;}else{}?>
								</p>
							</div>
						
							<div class="col-sm-3">
								<label class="control-label" for="focusedInput">Entrance Exam Taken</label>
								<p class="form-control-static">
									<? if(count($entranceexams)!='') {
										foreach($entranceexams as $entranceExam){ if( $entranceExam->entrance_exam_id == $details->entrance_exam){?>
										<? echo ucfirst($entranceExam->entrance_exam_name);?>
									<?} } }?>
								</p>
							</div>
							<div class="col-sm-3">
								<label class="control-label" for="focusedInput">Exam Rank</label>
								<p class="form-control-static">
									<? if(isset($details->entrance_rank) && $details->entrance_rank!='') {echo $details->entrance_rank;}else{}?>
								</p>
							</div>							
						</div>
						<div class="form-group">
							<div class="col-sm-3">
								<label class="control-label" for="focusedInput">Year</label>
								<p class="form-control-static">
									<? if(isset($details->which_year_1) && $details->which_year_1!='') {echo $details->which_year_1;}else{}?>
								</p>
							</div>
						
							<div class="col-sm-3">
								<label class="control-label" for="focusedInput">Entrance Exam Taken</label>
								<p class="form-control-static">
									<? if(count($entranceexams)!='') {
										foreach($entranceexams as $entranceExam){ if( $entranceExam->entrance_exam_id == $details->entrance_exam_1){?>
										<? echo ucfirst($entranceExam->entrance_exam_name);?>
									<?} } }?>
								</p>
							</div>
							<div class="col-sm-3">
								<label class="control-label" for="focusedInput">Exam Rank</label>
								<p class="form-control-static">
									<? if(isset($details->entrance_rank_1) && $details->entrance_rank_1!='') {echo $details->entrance_rank_1;}else{}?>
								</p>
							</div>							
						</div>
						<div class="form-group">
							<div class="col-sm-3">
								<label class="control-label" for="focusedInput">Year</label>
								<p class="form-control-static">
									<? if(isset($details->which_year_2) && $details->which_year_2!='') {echo $details->which_year_2;}else{}?>
								</p>
							</div>
						
							<div class="col-sm-3">
								<label class="control-label" for="focusedInput">Entrance Exam Taken</label>
								<p class="form-control-static">
									<? if(count($entranceexams)!='') {
										foreach($entranceexams as $entranceExam){ if( $entranceExam->entrance_exam_id == $details->entrance_exam_2){?>
										<? echo ucfirst($entranceExam->entrance_exam_name);?>
									<?} } }?>
								</p>
							</div>
							<div class="col-sm-3">
								<label class="control-label" for="focusedInput">Exam Rank</label>
								<p class="form-control-static">
									<? if(isset($details->entrance_rank_2) && $details->entrance_rank_2!='') {echo $details->entrance_rank_2;}else{}?>
								</p>
							</div>							
						</div>
					</div>
				</div>
			</div>
			<div class="panel panel-default">
				<div class="panel-heading" onclick="regTab1(5)">Under Graduate Information
				<i  id="icon5"class="glyphicon glyphicon-triangle-bottom  pull-right"></i></div>
				<div class="panel-body" id="tab_5_hide" style="display:none;">
				<div class="form-horizontal">
					<div class="form-group">
						<label for="select" class="col-sm-3 control-label">Degree Name</label>
						<div class="col-sm-8">
							<p class="form-control-static">
								<? if(count($b_degrees)!='') {
									foreach($b_degrees as $bachDegree){ if($bachDegree->degree_id == $details->bachelors_degree_name ){?>
									<? echo ucfirst($bachDegree->degree_name);?>
								<?}	}}?>
							</p>
						</div>
					</div>
					<div class="form-group">
						<label for="select" class="col-sm-3 control-label">University Name</label>
						<div class="col-sm-8">
							<p class="form-control-static">
								<? if(count($unversities)!='') {
									foreach($unversities as $unversity){ if( $unversity->unversity_id == $details->bachelors_university_name){?>
									<? echo ucfirst($unversity->unversity_name);?>
								<?}	}}?>
							</p>
						</div>
					</div>
					<div class="form-group">
						<label for="select" class="col-sm-3 control-label">College Name</label>
						<div class="col-sm-8">
							<p class="form-control-static">
								<? if(count($colleges)!='') {
									foreach($colleges as $college){ if($college->college_id == $details->bachelors_college){?>
									<? echo ucfirst($college->college_name);?>
								<?}	}}?>
							</p>
						</div>
					</div>
					<div class="form-group">
						<label for="select" class="col-sm-3 control-label">Specialization Name</label>
						<div class="col-sm-8">
							<p class="form-control-static">
								<? if(count($specializations)!='') {
								foreach($specializations as $specialization){ if($specialization->specialined_id == $details->bachelors_specialization){?>
									<? echo ucfirst($specialization->specialined_name);?>
								<?}	}}?>
							</p>
						</div>
					</div>
					<div class="form-group">
						<label for="select" class="col-sm-3 control-label">Year</label>
						<div class="col-sm-8">
							<p class="form-control-static">
									<? if(isset($details->bachelors_year_admission) && $details->bachelors_year_admission!='') {echo $details->bachelors_year_admission;}else{}?>
								</p>
						</div>
					</div>
				</div>
			</div>
			</div>
			<div class="panel panel-default">
				<div class="panel-heading" onclick="regTab1(6)">Post Graduate Information
				<i  id="icon5"class="glyphicon glyphicon-triangle-bottom  pull-right"></i></div>
				<div class="panel-body" id="tab_6_hide" style="display:none;">
					<div class="form-horizontal">
					<div class="form-group">
						<label for="select" class="col-sm-3 control-label">Masters Degree</label>
						<div class="col-sm-8">
							<p class="form-control-static">
								<? if(count($m_degrees)!='') {
									foreach($m_degrees as $masdegrees){ if($masdegrees->masters_degree_id == $details->masters_degree){?>
									<? echo ucfirst($masdegrees->mas_degree_name);?>
								<?}	}}?>
							</p>
						</div>
					</div>
					<div class="form-group">
						<label for="select" class="col-sm-3 control-label">Masters University</label>
						<div class="col-sm-8">
							<p class="form-control-static">
								<? if(count($unversities)!='') {
									foreach($unversities as $unversity){ if( $unversity->unversity_id == $details->masters_university){?>
									<? echo ucfirst($unversity->unversity_name);?>
								<?}	}}?>
							</p>
						</div>
					</div>
					<div class="form-group">
						<label for="select" class="col-sm-3 control-label">College Name</label>
						<div class="col-sm-8">
							<p class="form-control-static">
								<? if(count($colleges)!='') {
									foreach($colleges as $college){ if($college->college_id == $details->masters_college){?>
									<? echo ucfirst($college->college_name);?>
								<?}	}}?>
							</p>
						</div>
					</div>
					<div class="form-group">
						<label for="select" class="col-sm-3 control-label">Specialization Name</label>
						<div class="col-sm-8">
							<p class="form-control-static">
								<? if(count($specializations)!='') {
								foreach($specializations as $specialization){ if($specialization->specialined_id == $details->masters_specialization){?>
									<? echo ucfirst($specialization->specialined_name);?>
								<?}	}}?>
							</p>
						</div>
					</div>
					<div class="form-group">
						<label for="select" class="col-sm-3 control-label">Year</label>
						<div class="col-sm-8">
							<p class="form-control-static">
									<? if(isset($details->masters_year_admission) && $details->masters_year_admission!='') {echo $details->masters_year_admission;}else{}?>
								</p>
						</div>
					</div>
				</div>
				</div>
			</div>
			<div class="panel panel-default">
				<div class="panel-heading" onclick="regTab1(7)">Doctorate Information
				<i  id="icon5"class="glyphicon glyphicon-triangle-bottom  pull-right"></i></div>
				<div class="panel-body" id="tab_7_hide" style="display:none;">
					<div class="form-horizontal">
						<div class="form-group">
						<label for="inputcname" class="col-sm-3 control-label">PhD</label>
						<div class="col-sm-8">
							<p class="form-control-static">
								<? if(isset($details->doctorate_name) && $details->doctorate_name!='') {echo $details->doctorate_name;}else{}?>
							</p>
						</div>
						</div>
						<div class="form-group">
							<label for="select" class="col-sm-3 control-label">University Name</label>
							<div class="col-sm-8">
								<p class="form-control-static">
								<? if(count($unversities)!='') {
									foreach($unversities as $unversity){ if( $unversity->unversity_id == $details->doctorate_university){?>
									<? echo ucfirst($unversity->unversity_name);?>
								<?}	}}?>
							</p>
							</div>
						</div>
						<div class="form-group">
							<label for="select" class="col-sm-3 control-label">College Name</label>
							<div class="col-sm-8">
								<p class="form-control-static">
								<? if(count($colleges)!='') {
									foreach($colleges as $college){ if($college->college_id == $details->doctorate_college){?>
									<? echo ucfirst($college->college_name);?>
								<?}	}}?>
								</p>
							</div>
						</div>
						<div class="form-group">
							<label for="select" class="col-sm-3 control-label">Specialization Name</label>
							<div class="col-sm-8">
								<p class="form-control-static">
									<? if(count($specializations)!='') {
									foreach($specializations as $specialization){ if($specialization->specialined_id == $details->doctorate_specialization){?>
										<? echo ucfirst($specialization->specialined_name);?>
									<?}	}}?>
								</p>
							</div>
						</div>
						<div class="form-group">
						<label for="select" class="col-sm-3 control-label">Year</label>
						<div class="col-sm-8">
							<p class="form-control-static">
									<? if(isset($details->doctorate_year) && $details->doctorate_year!='') {echo $details->doctorate_year;}else{}?>
								</p>
						</div>
					</div>
					</div>					
				</div>
			</div>
		</div> 	</div>
		<input type="hidden" id="opentabId" value="1">
	</div>
</div>

<script> 
function regTab1(tabid){
var closeTadId=$('#opentabId').val();
$("#tab_"+closeTadId+"_hide").slideUp("slow");
$("#icon"+closeTadId).removeClass("glyphicon-triangle-top").addClass("glyphicon-triangle-bottom");
$("#tab_"+tabid+"_hide").slideDown("slow");
$("#icon"+tabid).removeClass("glyphicon-triangle-bottom").addClass("glyphicon-triangle-top");
$('#opentabId').val(tabid);
}
</script>
